### ISSUE TITLE
Passwords shown in log

### ISSUE THREAD

**Issue by aleksandrs-ledovskis** [ExchangeCalendar/exchangecalendar#100]
Despite "Show password in clear text in log file" checkbox being unchecked, authentication password is clearly visible in rows generated by observer activity.

Example:

`1st-setup:2017-9-0 23:39:4.594:edc07453-c547-ba4b-911c-8a6521acfea9: ecExchangeRequest observing http-on-modify-request for URI https://USERNAME:PASSWORD@outlook.office365.com/EWS/Exchange.asmx originalURI https://USERNAME:PASSWORD@outlook.office365.com/EWS/Exchange.asmx`

**Comment by Trim** [comment]
Hello,

I think that's due to the 52 release workaround.
We need to fix it, thanks !

**Comment by advancingu** [comment]
@Trim Can you provide a link to the commit or PR that caused this?

**Comment by Trim** [comment]
Yes, that was introduced by commit 7ff38490c460dfe70a64ff1ffc34e57e707dea5b which introduce the `observe()` function in `ExchangeRequest.js`.

The informations logged expose the full `URI.scheme` which contains username and password.

The fix I was writting (but currently not tested) is to construct the URL with all informations except password if the user want to hide it.

**Comment by master-lincoln** [comment]
Looks like this can be closed.

**Comment by Trim** [comment]
Indeed, it should be fixed with release 4.0.0-beta5.
