### ISSUE TITLE
Password shown in password request dialogue box

### ISSUE THREAD

**Issue by andyhhp** [ExchangeCalendar/exchangecalendar#103]
The password request dialogue box, which should normally read "Enter password for $ACCOUNT on $URL" substitutes the cached password for the account name.

Discovered after my password expired (/sigh corporate policy) and I was prompted for my new password.

Thunderbird 52.3.0 64bit: Debian
Lightning: 5.4

Reproduces on 4.0.0-beta 3 and 4.

**Comment by fthommen** [comment]
Confirmed on Mac OS X 10.11.6 (TB 52.4.0).  IMHO this should be tagged a critical bug, as it may expose your password to others very easily!

**Comment by joernrueffer** [comment]
Can also confirm this behavior with Debian 9 64bit, TB 52.3.0, Lighting 5.4.3 and both beta3 or beta4.

**Comment by laclaro** [comment]
Confirmed on Version 4.0.0-beta4 on Windows. It is shown both, the stored password (if stored previously) and the $ACCOUNT as mentioned above. This is important!

![testpasswort](https://user-images.githubusercontent.com/6398487/31879627-395bd052-b7de-11e7-8ca1-c3e205f381c1.jpg)

**Comment by laclaro** [comment]
I think it should be in this file, could not track it down though:
https://github.com/ExchangeCalendar/exchangecalendar/blob/master/interfaces/exchangeAuthPrompt2/mivExchangeAuthPrompt2.js

**Comment by McSvenster** [comment]
Same here (Ubuntu 17.10, TB 52.4.0 (64-Bit))

**Comment by bkaatz** [comment]
Seen on Gentoo, kernel 4.12.3, TB 52.4.0 (64-bit), Lightning 5.4, Exchange EWS 4.0.1002.

**Comment by Trim** [comment]
It should be fixed with release 4.0.0-beta5.
