### ISSUE TITLE
Papercut: change default branch

### ISSUE THREAD

**Issue by StianOby** [ExchangeCalendar/exchangecalendar#108]
Currently, the branch "master" is the default branch that appears when visiting https://github.com/ExchangeCalendar/exchangecalendar. If one stumbles upon this repository, it would therefore seem as if the project is completely inactive. The master branch hasn't seen a real commit for a year or so.

The current branch (ec-4.0) should be set as the default, since that is for all practical purposes the master branch. Today a lot of guesswork is needed for new users and developers that stumble upon thus repository.

**Comment by Trim** [comment]
Hello,

Thanks for the report, we've just discussed about that recently in the PR #98 and we'll switch back to master default development base when release 4.0 will be ready.

**Comment by StianOby** [comment]
Fantastic! I guess this issue can be closed then, or marked as a duplicate.
