### ISSUE TITLE
Co-worker calendars in Office365

### ISSUE THREAD

**Issue by Fjodor42** [ExchangeCalendar/exchangecalendar#114]
Hiya,

Previously, I have been able to see my co-workers' calendars under my "Calendar" folder, having subscribed to one calendar per co-worker (3 in total).

I just realised that as of now, I see my own appoinments for each of those, and when I try to edit the calendars, said folder only shows "Birthdays" and a holiday calendar that I have subscribed to via the Office365 web app.

The web app shows the calendars in question without problem, having them displayed under "People's Calendars" to the left.

I have already tried building from the ec-4.0 branch, yielding an exchangecalendar-v4.0.0-beta5.xpi file, but the problem persists.

Thunderbird is 53.4.0, Lightning is 5.4

**Comment by advancingu** [comment]
Works fine for me. Are you sure username and primary email are correct for the calendars in question? To see other users' calendars, enter their email address as `Primary email address` when setting up the calendar and also make sure that these users did share their calendar with you.
Please reopen in case this doesn't work.
