### ISSUE TITLE
Compatibility with Daily 64-bit 59+

### ISSUE THREAD

**Issue by phr00t** [ExchangeCalendar/exchangecalendar#124]
Thunderbird "Daily" 64-bit is much snappier & I'd like to use it as my "Daily" driver (pun intended). It uses Lightning 6.1a and has a Google provider which works flawlessly. However, the current 4.0.0-beta4 EWS provider doesn't work. It installs, but I can't create a new Exchange calendar. When selecting "Exchange" as a new calendar, the "Location" field remains complaining about entering a "valid location", although nothing is accepted there. It also breaks the process for adding Google Calendars, as the "Location" field remains for that option too. I have to disable the EWS 4.0.0-beta4 provider to add Google Calendars.

**Comment by Trim** [comment]
Well, we don't have resource to manage the beta release, we'll never have enough resource to follow dayli builds ;)

**Comment by phr00t** [comment]
Understandable.. although, maybe it is related to a 64-bit build, not that it is beta or daily? Is there anything I could do to make a 64-bit build of the same source & have better luck?

**Comment by Trim** [comment]
All the extension is only JavaScript code executed by Thunderbird: there's nothing to compile and it's architecture independent.

I'm using Thunderbird 64bits and I have no issue currently. Although, I'm using Thunderbird stable release. This summer I had made some modifications from Thunderbird beta release, you can find the source code here: https://github.com/ExchangeCalendar/exchangecalendar/tree/current-lightning-beta

**Comment by phr00t** [comment]
Are you on Linux/Mac? I'm on Windows & using 64-builds I found here:

https://www.m64.info/index.php/thunderbird-64-bit-download

... which I presume (and hope) are the same found here:

https://ftp.mozilla.org/pub/thunderbird/nightly/latest-comm-central/

Which version are you using, 52? I couldn't seem to find a stable 64-bit Thunderbird version that far back, but I admit to not digging too deeply, because I like using the latest. :)

I'll try building your latest & see if it helps...

**Comment by phr00t** [comment]
Tried it. Built 5.0.0 xpi. Still asks for a location when adding a new calendar, and now also does when selecting "Google", breaking that option too. When putting something in Location so I can click "Next", I get this error when "Next" is clicked:

"[Exception... "Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]"  nsresult: "0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE)"  location: "JS frame :: resource://calendar/modules/calUtils.jsm -> file:///C:/Users/Phr00t/AppData/Roaming/Thunderbird/Profiles/vdhy4v43.default/extensions/%7Be2fda1a4-762b-4020-b5ad-a41df1933103%7D/calendar-js/calCalendarManager.js :: createCalendar :: line 446"  data: no]"

Any advice would be appreciated, as I'm willing to spend a little time to try & fix this.

**Comment by massic80** [comment]
Hi, the same occurs on TB 57.0beta

**Comment by bonanza123** [comment]
@phr00t 
https://github.com/jobisoft/TbSync works for me on TB 58 beta
@Trim did you check whether a collaboration between both addons is possible?

**Comment by Trim** [comment]
I didn't know about this addon: as written in the readme, it uses the Active Sync API instead of the Web Services, so I don't think we'll have a lot to share, unfortunately.

**Comment by advancingu** [comment]
TB60+ progress is tracked in #178
