### ISSUE TITLE
Locking up Thunderbird 52.4.0 on start

### ISSUE THREAD

**Issue by phoenix87ta** [ExchangeCalendar/exchangecalendar#126]
With this add-on enabled in my Thunderbird 52.4.0 64-bit, the client locks up entirely on start. All panes are blank and no menu functions work. I end up having to start in safe mode and disable add-ons. As soon as I re-enable this add-on, the issue returns. I have an existing calendar that utilizes this add-on which has worked in the past.

**Comment by Trim** [comment]
We are looking for reproducible case on #141
