### ISSUE TITLE
Error: Could not find a matching lightning timezone

### ISSUE THREAD

**Issue by enzolis** [ExchangeCalendar/exchangecalendar#134]
Dear developers,

thanks for this nice plugin and your continuous effort for improvement.
Unfortunately during a code beautification round (https://github.com/ExchangeCalendar/exchangecalendar/commit/ab8152a4fd4dc6bc41d485859c845888dfd32a05) the file  exchangecalendar/interfaces/exchangeTimeZones/ewsTimesZoneDefinitions_2007.xml
was corrupted.
Actually entries like
<t:To Kind="Period">trule:Microsoft/Registry/Dateline Standard Time/1-Standard</t:To>
were wrapped into several lines thus not matching the period id in 
<t:Period Bias="PT12H" Name="Standard" Id="trule:Microsoft/Registry/Dateline Standard Time/1-Standard"/>
anymore.
It might be good to revert this and exclude this file from beautifying.

Best regards,
 Thimo

**Comment by Trim** [comment]
Hello,

Well seen, thanks.

This legacy code is quiet weird: it seems to suppose that values inner XML tags are exactly same identical to values in the id attributes. Although, it uses spaces in id attributes and IIRC XML doesn't take into account multiple spaces inside an inner value (like the HTML code).

I'm writing a pull request which will revert changes on this file and exclude it from the beautifier.

**Comment by enzolis** [comment]
Works for me with the latest release. Thanks!
