### ISSUE TITLE
Thunderbird and WebExtensions?

### ISSUE THREAD

**Issue by BenjamenMeyer** [ExchangeCalendar/exchangecalendar#136]
Creating this to track Thunderbird's announcement of using WebExtensions at some future unknown date:
- https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_57
- https://bugzilla.mozilla.org/show_bug.cgi?id=1396172

And for community awareness so we can try to get in the game ahead in case there is anything blocking, like with Firefox's move to WebExtensions and the Pandora/TabGroups functionality (which still isn't functional).

**Comment by TiZ-EX1** [comment]
Thunderbird 58 will drop XUL. Are we Webextensions here, or am I gonna have to keep a copy of the 57 series on my system? If this extension stops working, Thunderbird will legitimately become useless to me.

**Comment by TiZ-EX1** [comment]
Huh. I really hope that's true. I might have misinterpreted what I heard, in that person saying "the backend was being moved from XUL to WebEx." My bad if so.

**Comment by BenjamenMeyer** [comment]
@TiZ-EX1 the backend is the the part shared by Firefox and Thunderbird and that has already moved to WebExtensions only; but from the sounds of it Thunderbird devs are doing what they can to keep that from impacting their community. How that play out? We'll see.

**Comment by advancingu** [comment]
Progress will be tracked in #178
