### ISSUE TITLE
Failing to create build

### ISSUE THREAD

**Issue by advancingu** [ExchangeCalendar/exchangecalendar#145]
I was trying to create a build with `make release`, however two issues have occurred:

Actual:
* Currently the `release` make target pulls strings and commits them directly as part of a release.
* A hidden folder of my IDE gets pulled into the release artifact (xpi file).

Expected:
* After having recently spent some time looking at Transifex workflows outside of this project, I have come to the conclusion that localization strings must be pulled into the primary development branch (usually `master`, presently `ec-4.0` here) using a PR workflow to always permit building without surprises. Therefore, the `release` make target shall be changed so that no commits are made and no translation are pulled as part of the release build process. Pulling translations must be a separately initiated step leading up to a release.
* All hidden files and folders in the project repository folder, except those specifically included, shall not be integrated into release artifacts.

@Trim Ping

**Comment by Trim** [comment]
Hello,

Ok, no problem for me, I understand.

Although, if I remove the translation management from the `release` target, it finally just does these steps:
* run the `build` target (the default one when we call `make`)
* add a git tag
* ask to push manually the git tag

Maybe we can directly drop the `release` target and just use the `build` and manually `git tag` to create a new release ?

I'm doing 2 PR, so you can choose your prefered way.

**Comment by advancingu** [comment]
I kept the `release` target, however after merging #146 I noticed that the make echo text needs to be changed. It says `Now, if the release is well done, please run one "git push" to publish code ...` but `push` makes no sense anymore, so this part of the sentence should be removed.

**Comment by advancingu** [comment]
Also, the command to push a tag would be `git push origin v$(version)`. It doesn't work without specifying a remote target.
