### ISSUE TITLE
upgraded to 4.0.0-beta5 works but seeing some strange errors logged

### ISSUE THREAD

**Issue by chaplina** [ExchangeCalendar/exchangecalendar#152]
OS: FreeBSD 11.1
Thunderbird 52.6.0
Lightning 5.4.6
Exchange 2010 SP3

A couple of examples:

Failed to read 'syncFolderEventMessage' from chrome://exchangecalendar/locale/calExchangeCalendar.properties. Error: [Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIStringBundle.formatStringFromName]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: resource://calendar/modules/calUtils.jsm -> file:///home/chaplina/.thunderbird/gjtv5g8a.default/extensions/%7Be2fda1a4-762b-4020-b5ad-a41df1933103%7D/calendar-js/calUtils.js :: calGetString :: line 699"  data: no]  calUtils.js:705
	calGetString file:///home/chaplina/.thunderbird/gjtv5g8a.default/extensions/%7Be2fda1a4-762b-4020-b5ad-a41df1933103%7D/calendar-js/calUtils.js:705:9
	_syncFolderItemsOK file:///home/chaplina/.thunderbird/gjtv5g8a.default/extensions/exchangecalendar@extensions.1st-setup.nl/calendar/interface/exchangeCalendar/mivExchangeCalendar.js:8275:30
	_getSyncState/< file:///home/chaplina/.thunderbird/gjtv5g8a.default/extensions/exchangecalendar@extensions.1st-setup.nl/calendar/interface/exchangeCalendar/mivExchangeCalendar.js:8233:29
	_onRequestOk file:///home/chaplina/.thunderbird/gjtv5g8a.default/extensions/exchangecalendar@extensions.1st-setup.nl/common/interface/exchangeLoadBalancer/mivExchangeLoadBalancer.js:74:13
	myOk file:///home/chaplina/.thunderbird/gjtv5g8a.default/extensions/exchangecalendar@extensions.1st-setup.nl/common/interface/exchangeLoadBalancer/mivExchangeLoadBalancer.js:56:21
	_onSendOk resource://exchangecommon/erSyncFolderItems.js:236:25
	erSyncFolderItemsRequest/this.parent< resource://exchangecommon/erSyncFolderItems.js:87:13
	_onLoad resource://exchangecommon/ecExchangeRequest.js:945:17
	ExchangeRequest.prototype.sendRequest/< resource://exchangecommon/ecExchangeRequest.js:352:17

Failed to read 'resetEventMessage' from chrome://exchangecalendar/locale/calExchangeCalendar.properties. Error: [Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIStringBundle.formatStringFromName]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: resource://calendar/modules/calUtils.jsm -> file:///home/chaplina/.thunderbird/gjtv5g8a.default/extensions/%7Be2fda1a4-762b-4020-b5ad-a41df1933103%7D/calendar-js/calUtils.js :: calGetString :: line 699"  data: no]  calUtils.js:705
	calGetString file:///home/chaplina/.thunderbird/gjtv5g8a.default/extensions/%7Be2fda1a4-762b-4020-b5ad-a41df1933103%7D/calendar-js/calUtils.js:705:9
	_performReset file:///home/chaplina/.thunderbird/gjtv5g8a.default/extensions/exchangecalendar@extensions.1st-setup.nl/calendar/interface/exchangeCalendar/mivExchangeCalendar.js:4412:26
	_resetCalendar file:///home/chaplina/.thunderbird/gjtv5g8a.default/extensions/exchangecalendar@extensions.1st-setup.nl/calendar/interface/exchangeCalendar/mivExchangeCalendar.js:4300:13
	ecObserver.prototype.observe file:///home/chaplina/.thunderbird/gjtv5g8a.default/extensions/exchangecalendar@extensions.1st-setup.nl/calendar/interface/exchangeCalendar/mivExchangeCalendar.js:10844:17
	_onSave chrome://exchangecommon/content/exchangeSettings.js:372:9
	anonymous chrome://global/content/bindings/dialog.xml%20line%20380%20%3E%20Function:1:41
	_fireButtonEvent chrome://global/content/bindings/dialog.xml:381:28
	_doButtonCommand chrome://global/content/bindings/dialog.xml:349:28
	_handleButtonCommand chrome://global/content/bindings/dialog.xml:337:18
	_editExchangeSettings chrome://exchangecalendar/content/calendar-calendars-list.js:60:13
	oncommand chrome://messenger/content/messenger.xul:1:1

**Comment by chaplina** [comment]
"fixed" by renaming symlinks in TBIRDINSTALL/profile/extensions/exchangecalendar.../
cd addressbook/locale ; ln -s en_US en-US ; cd ../..
cd calendar/locale ; ln -s en_US en-US ; cd ../..
cd common/locale  ; ln -s en_US en-US ; cd ../..
cd emailtag/locale  ; ln -s en_US en-US ; cd ../..

**Comment by chaplina** [comment]
OK, completely removed the extension (including any files in the extension dir) and all preferences from prefs.js

the message has not reappeared

**Comment by Trim** [comment]
Hello,

Well, according to your logs, we have well an issue with the `mivExchangeCalendar.js` code:

> _syncFolderItemsOK file:///home/chaplina/.thunderbird/gjtv5g8a.default/extensions/exchangecalendar@extensions.1st-setup.nl/calendar/interface/exchangeCalendar/mivExchangeCalendar.js:8275:30

> _performReset file:///home/chaplina/.thunderbird/gjtv5g8a.default/extensions/exchangecalendar@extensions.1st-setup.nl/calendar/interface/exchangeCalendar/mivExchangeCalendar.js:4412:26

I've looked at line `8275` and the JavaScript code is looking for strings saved in the namespace `exchangecalendar` instead of `exchangecommon`:

```javascript
this.addActivity(calGetString("calExchangeCalendar", "syncFolderEventMessage", [creations.length, updates.length, deletions.length, this.name], "exchangecalendar"), "", erSyncFolderItemsRequest.argument.actionStart, Date.now());
```

Same thing happened with line `4412`:

```javascript
this.addActivity(calGetString("calExchangeCalendar", "resetEventMessage", [this.name], "exchangecalendar"), "", this.resetStart, Date.now());
```

From the root source directory, I've ran this command to check if there was another code looking for strings in the file `calExchangeCalendar.properties`:

```bash
adrien@bureau-ado:~/code/exchangecalendar$ egrep -rni --exclude-dir .git '\s*GetString\s*\(\s*"calExchangeCalendar"' -l
calendar/content/calendar-calendars-list.js
calendar/content/messenger_task_delegation.js
calendar/interface/exchangeCalendar/mivExchangeCalendar.js
common/content/exchangeSettingsOverlay.js
common/content/manageEWSAccounts.js
common/content/oofSettings.js
```

Well, it seems, that some files that are located in common/ tree requires these transalations too.

I see these solutions:
* moving the properties files to the exchangecalendar namespace
* updating all source code of the files above to use the exchangecommon namespace in their `getString`  method call
* split the file into two files if possible to better split common and calendar parts of the module

Thanks for the report !

**Comment by msfox** [comment]
Hello, 
I have the same problem. Your Solution is from 4 Feb. But the Release 4.0.0-beta5 was from 29. Jan.
https://github.com/ExchangeCalendar/exchangecalendar/releases

Can you release a new Version, with fixed problem. 

For some time, I don't update Thunderbird (31.6.0) Lightning 3.3.3 in ProdSystem, because in sandboxsystem Thunderbird 52.9.1 / Lighning 5.4.9.1 and ExchangeCalendar 4.0.0-beta5 doesn't work.

Thanks a lot
