### ISSUE TITLE
Building for Debian - install-xpi failed

### ISSUE THREAD

**Issue by Mechtilde** [ExchangeCalendar/exchangecalendar#159]
I try to build exchangecalendar for Debian:

I got this error messsage:
"install-xpi: Error while parsing install.rdf: 'file   install.rdf
no such file"

I looked into the Makefile and found in line 12. 
As I understand it, 'install.rdf should be executed. This fails.
How should it be fixed
Kind regards
Mechtilde

**Comment by Trim** [comment]
Hello,

Firts, thanks for your support with Debian packaging.

As I understand, this error message doesn't come from the Makefile rules (as I assumed when I was reviewing the PR #160), but from the Debian XPI building system.

Actually, we don't use any more directly an `install.rdf` file, but we build it from the `install.template.rdf` and `VERSION` file.

If the `install-xpi` rule needs to be used, you need to manually create the `install.rdf` file with a commands like:

```bash
version=$(cat VERSION)
sed 's/@VERSION@/${version}/g' <install.template.rdf >install.rdf
```

I've just found the `rules` file from https://anonscm.debian.org/cgit/collab-maint/calendar-exchange-provider.git/tree/debian/rules . I see you also need to update:
  * interfaces location for the `TYPELIB` variable (they are now located in different sub-folders)
  * list of files to exclude from the `install-xpi` directive

I've never used the Debian build system myself, so I need to test it on my computer. Until then, I won't be able to be more accurate than that, sorry.

**Comment by Trim** [comment]
I was able to build the package for Debian by following these steps:

1. Download latest 4.0.0-beta5 tarball from https://github.com/ExchangeCalendar/exchangecalendar/releases
2. Clone Debian git repo: https://anonscm.debian.org/git/collab-maint/calendar-exchange-provider.git
3. From the cloned repo, import the new tarball with `gbp import-orig ../exchangecalendar-v4.0.0-beta5.xpi`
4. Adding a file `debian/source/include-binaries` to add exceptions for all GIF and PNG files from the tarball
5. Updating the rules file with:

```diff
commit b0aa6d1de38f226223883f28848216df32f405fb
Author: Adrien Dorsaz <adrien@adorsaz.ch>
Date:   Wed Feb 14 00:19:45 2018 +0100

    update rules with new directory tree

diff --git a/debian/rules b/debian/rules
index 25f529a..e103fcb 100755
--- a/debian/rules
+++ b/debian/rules
@@ -4,9 +4,9 @@
 
 TYPELIB := python /usr/lib/thunderbird-devel/sdk/bin/typelib.py \
  -I"/usr/lib/thunderbird-devel/idl" \
- -I"interfaces/exchangeAddressBook/exchangeAbCard" \
- -I"interfaces/exchangeBaseItem" \
- -I"interfaces/exchangeTimeZones"
+ -I"addressbook/interface/exchangeAbCard" \
+ -I"common/interface/exchangeBaseItem" \
+ -I"calendar/interface/exchangeTimeZones"
 
 TOPDIRS := $(shell ls -d */)
 
@@ -20,7 +20,7 @@ override_dh_auto_build:
        dh_auto_build
 
 override_dh_auto_install:
-       install-xpi -x 'chrome/skins/fugue/Fugue Icons README.txt' \
+       install-xpi -x 'common/theme/common/images/Fugue Icons README.txt' \
                $$(find $(TOPDIRS) -name *.idl -printf '-x %p ') \
                -x CHANGELOG.md \
                -x license.txt \
```
6. Bumping debian version and update Debian change log with `gbp dch`
7. Finally building the package with `gbp buildpackage`

You can see all changes I've made on the debian packaging on [my personal repostiory](https://projects.adorsaz.ch/adrien/exchangecalendar-debian/commits/master)

**Comment by Trim** [comment]
Hi @Mechtilde,

Did the process mentioned above worked for you ?
If not, could you share with us how you are building the extension for Debian, so I could help you ?

Note, that, if you want to do yourself a release with the current ec-4.0 branch, you need to update the `VERSION` file with the release name you want to get and then run `make`.

**Comment by Mechtilde** [comment]
Hello Adrian,

i will do it ASAp.

sorry for my limited time.



Am 25.02.2018 um 10:13 schrieb Adrien Dorsaz:
> Hi @Mechtilde,
> 
> Did the process mentioned above worked for you ?
> If not, could you share with us how you are building the extension for Debian, so I could help you ?
> 
> Note, that, if you want to do yourself a release with the current ec-4.0 branch, you need to update the `VERSION` file with the release name you want to get and then run `make`.
> 
Regards
-- 
Mechtilde Stehmann
## Apache OpenOffice
## Freie Office Suite für Linux, MacOSX, Windows
## Debian Developer
## Loook, calender-exchange-provider, libreoffice-canzeley-client
## PGP encryption welcome
## F0E3 7F3D C87A 4998 2899  39E7 F287 7BBA 141A AD7F

**Comment by advancingu** [comment]
@Mechtilde Is this resolved?

**Comment by advancingu** [comment]
Closing due to lack of response.
