### ISSUE TITLE
Calendars from public folders not working correctly

### ISSUE THREAD

**Issue by edwin-v** [ExchangeCalendar/exchangecalendar#161]
This is actually a long standing issue that has existed since this plugin moved from 1stsetup.

Newly created events in calendars from "public folders" won't appear unless you manually clear the cache.

Delete event is greyed out in the context menu of events. The 'delete' function from the event window does work.

I also get a lot of "Failed to read '*' from chrome://exchangecalendar/locale/calExchangeCalendar.properties." where * varies, but often has syncFolderEventMessage. I'm not sure if this is related or separate.

TB 52.6.0 / Lightning 5.4.6 / 4.0.0-beta5

**Comment by simonschmeisser** [comment]
Same here (5.0.0 alpha 2 as well), any hints where to start debugging?

**Comment by simonschmeisser** [comment]
I'm currently having a closer look but I'm completely new to all of complex JS, thunderbird, lightning, exchange ... so might need some help sooner or later

When I add or remove an item in a public calendar I get an error in
mivExchangeCalendar.js at line 8344
`
"1st-setup: (gemeinsam) Changes could not be made.publicfoldersroot1: [jar:file:///home/simon/.thunderbird/cem7dttz.default/extensions/exchangecalendar@extensions.1st-setup.nl.xpi!/calendar/interface/exchangeCalendar/mivExchangeCalendar.js:10651] _logError2: [jar:file:///home/simon/.thunderbird/cem7dttz.default/extensions/exchangecalendar@extensions.1st-setup.nl.xpi!/calendar/interface/exchangeCalendar/mivExchangeCalendar.js:8344] _syncFolderItemsOK3: [jar:file:///home/simon/.thunderbird/cem7dttz.default/extensions/exchangecalendar@extensions.1st-setup.nl.xpi!/calendar/interface/exchangeCalendar/mivExchangeCalendar.js:8274] _getSyncState/<4: [jar:file:///home/simon/.thunderbird/cem7dttz.default/extensions/exchangecalendar@extensions.1st-setup.nl.xpi!/common/interface/exchangeLoadBalancer/mivExchangeLoadBalancer.js:74] _onRequestOk5: [jar:file:///home/simon/.thunderbird/cem7dttz.default/extensions/exchangecalendar@extensions.1st-setup.nl.xpi!/common/interface/exchangeLoadBalancer/mivExchangeLoadBalancer.js:56] myOk6: [resource://exchangecommon/erSyncFolderItems.js:247] _onSendOk7: [resource://exchangecommon/erSyncFolderItems.js:84] erSyncFolderItemsRequest/this.parent<8: [resource://exchangecommon/ecExchangeRequest.js:875] _onLoad9: [resource://exchangecommon/ecExchangeRequest.js:340] sendRequest/<"

`
`this.logError("Changes could not be made." + erSyncFolderItemsRequest.folderBase);`

so apparently `folderBase` is not `calendar` as expected by the switch case above but rather `publicfoldersroot1`

**Comment by advancingu** [comment]
@edwin-v @simonschmeisser Are the events in question immediately inside the `publicfoldersroot` or inside a subdirectory? Can you also tell me what `this.folderClass` is when the [switch statement](https://github.com/ExchangeCalendar/exchangecalendar/blob/v5.0.0-beta1/calendar/interface/exchangeCalendar/mivExchangeCalendar.js#L8333) is called?

See also https://docs.microsoft.com/en-us/dotnet/api/microsoft.exchange.webservices.data.wellknownfoldername?view=exchange-ews-api and https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxosfld/68a85898-84fe-43c4-b166-4711c13cdd61 for additional information.

**Comment by simonschmeisser** [comment]
Running the version with my PR #268 

`this.folderClass: "IPF.Appointment"`
`erSyncFolderItemsRequest.folderBase: "publicfoldersroot"`

Our public folder contains two Items: a calendar and an address book, I guess updates to the address book also end up here. I see no clue about the exact folder.

![grafik](https://user-images.githubusercontent.com/372442/57570077-7dbdf800-73fe-11e9-8c54-21abb46b32d5.png)

I cannot test changing something in the contacts as the exchange web interface is so broken I don't dare using it and exchangecalendar is read only

@advancingu should I update my PR to consider the `this.folderclass` as well?

**Comment by advancingu** [comment]
@simonschmeisser Please try my fix in #276. I've replaced the folder names with the class type to determine the type of synchronization needed. Hopefully this works.

**Comment by simonschmeisser** [comment]
@advancingu that works well and might even fix some other bugs, thanks!

**Comment by advancingu** [comment]
Should be fixed now.
