### ISSUE TITLE
Check server and mailbox gives error: "Failed to read 'ecErrorServerAndMailboxCheck' from chrome://exchangecalendar/locale/calExchangeCalendar.properties."

### ISSUE THREAD

**Issue by finsterwalder** [ExchangeCalendar/exchangecalendar#174]
When I try to add a new Exchange Calendar, I enter the Server URL, Primary email and username and klick [Check server and mailbox].
Then I get the error message:
Failed to read 'ecErrorServerAndMailboxCheck' from chrome://exchangecalendar/locale/calExchangeCalendar.properties.

Thunderbird 52.7.0 (64-Bit) on Linux Ubuntu
Lightning 5.4
Exchange Calendar 4.0.0-beta5

This used to work. I don't know whether Thundbird was upgraded...

**Comment by finsterwalder** [comment]
I just fixed the problem for me.
I removed all the passwords stored for exchange users.
You can manage your password in the Thunderbird Preferences -> Security -> Saved Passwords
After doing so, I re-added my calendar and it works fine.

So there seams to be an authentication problem underneath this issue.
A failed authentication should open a password request window in Thunderbird, to ask for a corrected password.

**Comment by ednarb29** [comment]
I have the same problem (and exactly the same software versions) but the purposed fix did not work for me. Any suggestions?

**Comment by rkoktan** [comment]
Same issue here... workaround provided above does not work for me.  Any idea when the next beta, or final release will arrive?

TB 52.9.1 (64-bit)
Lightning 5.4
Exchange Calendar 4.0.0-beta5

**Comment by rkoktan** [comment]
Same issue with beta6... no joy.

TB 52.9.1 (64-bit) on OpenSUSE LEAP 15
Lightning 5.4
Exchange Calendar 4.0.0-beta6

**Comment by Mechtilde** [comment]
Hello,

Am 17.08.2018 um 15:29 schrieb rkoktan:
> Same issue with beta6... no joy.
> 
> TB 52.9.1 (64-bit) on OpenSUSE LEAP 15
> Lightning 5.4
> Exchange Calendar 4.0.0-beta6

Where do you get this version from?

-- 
Mechtilde Stehmann
## Debian Developer
## calender-exchange-provider
## PGP encryption welcome
## F0E3 7F3D C87A 4998 2899  39E7 F287 7BBA 141A AD7F

**Comment by rkoktan** [comment]
From the main exchangecalendar page on Github, click the green "Clone or download" button, then click the blue "Download ZIP" button.  Extract the ZIP and in the resulting folder the README indicates v4.0.0-beta6.

**Comment by rkoktan** [comment]
I can confirm the "fix" [https://github.com/ExchangeCalendar/exchangecalendar/pull/189#issuecomment-418696365] works for me on TB60.  Calendar is good, and though I can create a Office 365 address books now, I don't see it under my Contacts folder, but whatever, happy about the calendar!

**Comment by advancingu** [comment]
This appears to be working now. Please reopen with Thunderbird developer console output in case problem persists. Thank you.
