### ISSUE TITLE
XML Parsing Error opening calendar event

### ISSUE THREAD

**Issue by mgrojo** [ExchangeCalendar/exchangecalendar#175]
After upgrading to Thunderbird 52.7.0 (64-bit) (CentOS 6.9), the following error appears when opening a calendar event:

![image](https://user-images.githubusercontent.com/13812910/39048168-caccdd10-449c-11e8-8169-084bfb92b77f.png)

``XML Parsing Error: undefined entity
Location: chrome://calendar/content/calendar-summary-dialog.xul
Line Number 235, Column 13:            <label value="&read.only.attachments.label;"
------------^``

Exchange Calendar Version: 4.0.0-beta5
Lightning version: 5.4.7

**Comment by david0fc** [comment]
Same with me (from previous tree https://github.com/Ericsson/exchangecalendar/issues/624):

Using
Fedora 27
Thunderbird 52.7.0
Lightning 5.4.7
EWS 3.9.0

My calendar is in an Office365 cloud.

When I try to create a new event, either with Ctrl+I, or right-clicking on a calendar day and selecting "New Event...", I get a window with the following error:

``` 
XML Parsing Error: undefined entity
Location: chrome://lightning/content/lightning-item-iframe.xul
Line Number 115, Column 7:
      <button id="counter-proposal-btn"
------^
```

When running thnderbird from the command line, I also get:

```
JavaScript strict warning: chrome://exchangecalendar/content/exchService-common-sets.js, line 129: ReferenceError: reference to undefined property "itemClass"
JavaScript error: chrome://exchangecalendar/content/calendar-event-dialog.js, line 98: TypeError: this._document.getElementById(...) is null
1st-setup:2018-3-2 15:19:23.890:  -- It is an Exchange Calendar event:null
1st-setup:2018-3-2 15:19:23.892:  -- Could not add exchange attachment buttons:TypeError: this._document.getElementById(...) is null
1st-setup:2018-3-2 15:19:23.892:exchWebService.attachments.addAttachmentsFromItem: foutje:TypeError: documentLink is null
1st-setup:2018-3-2 15:19:23.892:exchWebService.attachments.addAttachmentsFromItem: title:null
1st-setup:2018-3-2 15:19:23.892:No attachments
```
[ewslog.txt](https://github.com/Ericsson/exchangecalendar/files/1920256/ewslog.txt)


I reckon this used to happen before with some other EWS version, but it was a long time ago.

Any clue? Any additional info needed?

**Comment by jcengelsen** [comment]
I had the same problem!

My solution was to uninstall and install the Ligtning addon and 
everything worked fine.

JC

**Comment by mgrojo** [comment]
Thanks, @jcengelsen. It seems then a bug in Lightning, not ExchangeCalendar. In fact, from the Fedora version of Lightning. I've found now this:
https://bugzilla.mozilla.org/show_bug.cgi?id=1424197
https://bugzilla.redhat.com/show_bug.cgi?id=1525361

I'll close this issue, since the conversation can nevertheless follow.
