### ISSUE TITLE
Incompatible with version 60.0

### ISSUE THREAD

**Issue by mcarlton00** [ExchangeCalendar/exchangecalendar#185]
Just received the update to Thunderbird 60.0 on an Arch install and the plugin is reporting as no longer being compatible

**Comment by herzogmedia** [comment]
yes, this is discussed in #178 
hopefully there will be a solution (referenced in #182) 
but until then, we need to stick with tb 59 if we want to use the plugin

**Comment by mcarlton00** [comment]
I had looked through the previous discussion about merging the plugins, but I'm not sure how I missed 178.  Closing this as a duplicate
