### ISSUE TITLE
ExchangeCalendar incompatible with Thunderbird 60

### ISSUE THREAD

**Issue by mjklemm** [ExchangeCalendar/exchangecalendar#187]
ExchangeCalendar seems incompatible with Thunderbird 60.  I have tried to use extensions.strictCompatibility=false, but then ExchangeCalendar fails to open the Exchange calendar on outlook.com:

Error Code: 0x80570015
Description: [Exception... "Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]"  nsresult: "0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE)"  location: "JS frame :: jar:file:///C:/Users/Michael/AppData/Roaming/Thunderbird/Profiles/scn1ddjr.default/extensions/%7Be2fda1a4-762b-4020-b5ad-a41df1933103%7D.xpi!/components/calItemModule.js -> resource://calendar/calendar-js/calCalendarManager.js :: createCalendar :: line 445"  data: no]

Version of ExchangeCalendar is the latest commit from the master branch (4.0.0-beta6).

**Comment by Mechtilde** [comment]
Hello,



Am 10.08.2018 um 21:51 schrieb Michael Klemm:
> ExchangeCalendar seems incompatible with Thunderbird 60.  I have tried to use extensions.strictCompatibility=false, but then ExchangeCalendar fails to open the Exchange calendar on outlook.com:

You can try https://github.com/jobisoft/TbSync
> 
> Error Code: 0x80570015
> Description: [Exception... "Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]"  nsresult: "0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE)"  location: "JS frame :: jar:file:///C:/Users/Michael/AppData/Roaming/Thunderbird/Profiles/scn1ddjr.default/extensions/%7Be2fda1a4-762b-4020-b5ad-a41df1933103%7D.xpi!/components/calItemModule.js -> resource://calendar/calendar-js/calCalendarManager.js :: createCalendar :: line 445"  data: no]
> 
Regards
-- 
Mechtilde Stehmann

## PGP encryption welcome
## F0E3 7F3D C87A 4998 2899  39E7 F287 7BBA 141A AD7F

**Comment by mjklemm** [comment]
I saw TbSync but did not try it, as I had thought Outlook.com deprecated support for EAS.  But I was wrong. :-)  Thanks for the reminder!

Anyways, the bug report is still valid although TbSync now seems to work for me.

**Comment by herzogmedia** [comment]
this is discussed in #178

**Comment by mjklemm** [comment]
Thanks for pointing to #178.  I'll close this one.
