### ISSUE TITLE
Colorpick on calender creation doesn't work

### ISSUE THREAD

**Issue by geektoor** [ExchangeCalendar/exchangecalendar#19]
Heya,

this is an "old" bug, but your version also seem to include it.

If you add a new calender, you can select a color for the calendar. But after successfull adding it to your calendarlist, it stil has the default color. If you change it afterwards, everything is nice and fine.

So, just cosmetic, but annoying :)

Cheers,
Sven

**Comment by Trim** [comment]
Thanks for the report 👍

**Comment by advancingu** [comment]
Release [4.0.0-beta3](https://github.com/ExchangeCalendar/exchangecalendar/releases/tag/v4.0.0-beta3) should fix this issue.
