### ISSUE TITLE
Current release (4.0.0) not compatible with latest Ubuntu thunderbird (60.2.1)

### ISSUE THREAD

**Issue by dlpartain** [ExchangeCalendar/exchangecalendar#198]
Greetings,

I updated to thunderbird 60.2.1 on Ubuntu today, and the plugin stopped working.  I grabbed the latest version of the plugin (4.0.0) and tried installing it, and got:

"Exchange Calendar could not be installed because it is not compatible with Thunderbird 60.2.1"

Is this a known issue?  Any thoughts on if / how / when it can be addressed?

Thanks.

David

**Comment by dal00** [comment]
Pullrequest #189 was merged into v5.0.0-alpha1 and has some initial fixes for this. Does not look like there is any release for this yet.

**Comment by SillonBono** [comment]
I just updated Thunderbird and found that Ubuntu thought it is a good idea to upgrade Thunderbird to v60 which breaks tons of add ons not just this one.

downgrade while you can by using:

apt-get install --reinstall thunderbird=1:52.7.0+build1-0ubuntu1

My advise, for the time being pin thunderbird:
In the file "/etc/apt/preferences" put:

Package: thunderbird
Pin: version 1:52.7.0+build1-0ubuntu1
Pin-Priority: 1001

Stupid Mozilla changing the innards of Thunderbird for things that are of no benefit for the users, like everything they do.

**Comment by dlpartain** [comment]
Yes, absolutely!  This plugin keeps me sane at work.  I'm very very happy that there are people who know enough and are willing to spend their time on this!

**Comment by SillonBono** [comment]
Is there a patreon (or similar) to help fund this project? I won't mind throwing a few dollars to the authors.

**Comment by advancingu** [comment]
Hi @SillonBono, I finally set up a Patreon so that I can spend more time on this project again: https://www.patreon.com/advancingu Thanks already in case you decide to contribute!

**Comment by advancingu** [comment]
I just published an official first alpha of version 5 that includes support for Thunderbird 60. Please continue the discussion in https://github.com/ExchangeCalendar/exchangecalendar/issues/178
