### ISSUE TITLE
A recent update to thundirbird 60.2.1 stopped this plugin to work

### ISSUE THREAD

**Issue by AkhilSinghRana** [ExchangeCalendar/exchangecalendar#200]
Hi,
 
My Thundirbird got updated recently. After update to 60.2.1 this Exchange plugin and lightning calendar does not work.

I found a workaround for lightning calendar, by just removing it from thundirbird plugins and installing "xul-ext-lightning" via apt install command. However, the Exchange calendar is still not supported. 

Anyone else has the same issue? any help is appreciated

Thanks,
Akhil

**Comment by minibiti** [comment]
Have a look at Issue 178. https://github.com/ExchangeCalendar/exchangecalendar/issues/178

**Comment by advancingu** [comment]
Yes, this issue is covered in #178.

**Comment by advancingu** [comment]
@AkhilSinghRana Use the 5.0.0-alpha1 release for a compatible version.

**Comment by AkhilSinghRana** [comment]
Thanks everyone. It worked when I build 5.0.0-alpha1 release.
