### ISSUE TITLE
Not all appointments are shown in Calendar

### ISSUE THREAD

**Issue by advancingu** [ExchangeCalendar/exchangecalendar#203]
Expected:
* All calendar events shall be shown.

See previous discussions such as:
* https://github.com/ExchangeCalendar/exchangecalendar/issues/178#issuecomment-431026165
* https://github.com/ExchangeCalendar/exchangecalendar/issues/178#issuecomment-431030840
* https://github.com/ExchangeCalendar/exchangecalendar/issues/178#issuecomment-431036170

**Comment by zioalex** [comment]
Same problem here. Some events are not showed on Friday.

**Comment by zioalex** [comment]
I tried the alpha2 and to me now it seems okay. All the events are there. Fridays included :-)

**Comment by advancingu** [comment]
I would imagine that this will not remain that way. 5.0.0-alpha2 does not contain any changes other than logging at the moment, so probably you were lucky with some timing problems in the add-on.

**Comment by David-S-Morgan** [comment]
@advancingu I did install PR #202 without issue.  Any tips/pointers on gathering logging info or any tests you would suggest I run?

**Comment by Bugeater327** [comment]
I built the v5.0.0-alpha1 version just now.  I'm seeing similar issues about missing meetings too.
My missing events are not just on Friday.
I also have a meeting with an attachment in Exchange.  I see no info about the attachment in TB.

**Comment by fbicknel** [comment]
Similar conversation going on over at the [Mozilla forum](https://support.mozilla.org/en-US/questions/1237336#answer-1166285).

The alpha2 branch points to the same commit as the alpha1 branch. Erm, but _not_ the same commit as the alpha1 tag.  :-/

**Regarding the missing Fridays and weekend appointments:**
So, interestingly, I can create new calendar items for Fridays. I can do so either from TB or from OWA and they sync up.

It's just all those pre-existing ones that were there before I set up TB+Lightning+Exchange that stubbornly refuse to show up.

**Comment by fbicknel** [comment]
I think it has something to do with repeating appointments. Those seem to be the ones affected. And I can create a singleton appointment any time, it seems. If I create one in TB that repeats, it just disappears and doesn't do anything to the calendar, either locally or on the server. Hm...

**Comment by fbicknel** [comment]
Oh really?  :)
![image](https://user-images.githubusercontent.com/1676056/47382951-899bd400-d6d1-11e8-91c7-3fb290f57259.png)
Foovent was created as a single event. Then edited to make it repeat daily for about 4 days or so. It disappeared. But when I searched for it in events, it showed up ... on the first day only. I tried editing it, and it still thinks its a repeating event. This is so strange. Ok... looks like the server does think it's a repeating event and it shows up there (so my comment above is likely premature).

**Comment by advancingu** [comment]
@fbicknel The difference in commits between tag and branch 5.0.0-alpha1 should be cosmetic only (going from memory). I currently have a [PR open](https://github.com/ExchangeCalendar/exchangecalendar/pull/202) against 5.0.0-alpha2 so already had to push this branch to have a target.

@all Personally I was able to get some additional events to show up by clearing the calendar cache. This can be done via Calendar context menu -> `Exchange (EWS) properties` -> `Offline caching` -> `Clear offline cached data`. My next goal will be to check the caching code for issues. Overall the code is in pretty bad shape so I wouldn't be surprised if this implementation was buggy.

**Comment by Bugeater327** [comment]
@advancingu, hmmm, that made more events disappear.
I'm on 5.0.0-alpha1 of the Exchange Calendar plugin and TB 60.2.1.

**Comment by chaosblog** [comment]
I used the clear cache before, the events disappeared and after a while they were synced. 
Since my calendar isn't that full at the moment I can't give a prediction what pattern the missing items have.

Currently I miss an event with this properties:
-  single event
- scheduled on a Tuesday
- created by someone else
- 2 attendees
- 1 attachment

**Comment by benwaugh** [comment]
Having cleared the cache, I am now missing at least one event that was there before! Thanks to @advancingu for all your work trying to fix this!

**Comment by tobiasreischmann** [comment]
I have a slightly different problem. In my scenario delegated calendars with a small set of privileges are not synced at all. I have a first initial work in progress solution, which solves my problem in some cases. See #206 . Maybe the to phenomena have the same underlying problem and my changes fix this issue here. Would be nice, if someone could test it.

**Comment by advancingu** [comment]
I merged #202 so hopefully log output is now more easily obtainable. #206 still needs some work.

**Comment by ownclouduser** [comment]
I experience the same issue however I can't really point it down to any particular constellation. 

Do I miss something or is it the case that there is no "debug option" in the property panel of v5.0.0? Thanks.

**Comment by sebix** [comment]
> Do I miss something or is it the case that there is no "debug option" in the property panel of v5.0.0? Thanks.

Open the Hamburger-Menu, _Add-Ons_, _Lightning_, _Exchange (EWS)_ tab, _Logging_ tab

**Comment by sebix** [comment]
See also https://github.com/ExchangeCalendar/exchangecalendar/tree/v5.0.0-alpha2#obtaining-log-output (it's kind of hidden, because that phrase is not in the master branch)

**Comment by bathmatt** [comment]
I'm seeing similar issues, I believe that any meeting I accept on the web-interface to outlook is not in my t-bird cal.  I'm using alpha2 and TB60 on RHEL 7

**Comment by jethrogb** [comment]
I installed the latest git master and enabled level 2 logging. The missing calendar items are not mentioned at all in the logs.

**Comment by jethrogb** [comment]
`convertExchangeToCal` never returns when processing the items in question.

**Comment by jethrogb** [comment]
I'm not sure where to go from here, I hope this is enough information to fix the bug?

**Comment by Trim** [comment]
Hello,

> cal.makeURL is not a function

IIRC, cal should be a shortcut for calendar utils from Lightning and makeURL would a method from these utils. Maybe Lightning has moved this method to another place ?

According to current ExchangeCalendar source code (v 5.0.0-alpha2), it seems the only occurence of `cal.makeURL` was on line 2894 of _common/interface/exchangeBaseItem/mivExchangeBaseItem.js_.

That's a code which is creating an URL for attachment with the base URL _http://somewhere_.
It would be good to fix this method call and remove this bad domain _somewhere_ and use a really not real domain like _example.com_.

**Comment by Trim** [comment]
I wasn't able to reproduce the bug, so it will be good if you can try code inside the PR 219 :-)

**Comment by jethrogb** [comment]
With #219, some events that were missing before are now showing up correctly for me.

**Comment by advancingu** [comment]
@ everyone Please check `v5.0.0-alpha2` that I just released. If the issue is not fixed there, please reopen.
