### ISSUE TITLE
External out of office reply input field has no scroll-bar, internal does

### ISSUE THREAD

**Issue by Thomas-1985** [ExchangeCalendar/exchangecalendar#207]
Hi

Thunderbird: 52.9.1 x86
Plugin: 4.0.0

I just noticed that when setting an out-of-office reply, the external input field has no scrollbar when the text gets longer. The internal one does however.
Hopefully its an easy fix :)

Best,
Thomas

**Comment by advancingu** [comment]
@Thomas-1985 Can you please provide a screenshot?

**Comment by Thomas-1985** [comment]
Sure ;)

![exchangecalendar](https://user-images.githubusercontent.com/9249624/47707651-a9c91700-dc2c-11e8-9f89-45e4479b29ea.jpg)

**Comment by advancingu** [comment]
Cannot reproduce with latest version.
