### ISSUE TITLE
Thunderbird 60 disables Exchange Calendar

### ISSUE THREAD

**Issue by a9db0** [ExchangeCalendar/exchangecalendar#208]
Upgraded to Thunderbird 60, no more Exchange Calendar.  I noted in the changelog that there was a max version limit set to 59.  Does this just need to be updated, or are there architectural changes in TB that cause incompatibilities?

**Comment by advancingu** [comment]
Please see https://github.com/ExchangeCalendar/exchangecalendar/blob/master/README.md . There is an alpha release for TB 60. A number of APIs in TB have changed.

**Comment by a9db0** [comment]
>> A number of APIs in TB have changed.
That's what I suspected.  Thanks for the prompt reply, and the work you are all doing to make it compatible with v60.  I'll check out the alpha.
