### ISSUE TITLE
starting ends up in non-resposive state

### ISSUE THREAD

**Issue by pfps** [ExchangeCalendar/exchangecalendar#21]
It's great that some work is being done on Exchange compatability.   This new version had been working for me up until just now, although start times were long.

However, now after startup thunderbird is not showing emails and is non-responsive - the submenus pop up but clicking on the entries doesn't do anything.   Disabling the EWS add-on (start in safe mode, disable the add-on, and then restart) returns to a workable state (but of course without my Exchange calendar).  Re-enabling goes back to the broken state.

I am running thunderbird with output to an emacs buffer and I can see the Exchange requests happening, so it is not that thunderbird is completely wedged, just that the interface isn't working except for the close button.  

Any suggestions on what could be going wrong?   I'm running Thunderbird 52.1.0 (64-bit) under Fedora 25 with XFCE.

![screenshot_2017-06-14_14-15-16](https://user-images.githubusercontent.com/6618235/27155379-a18ecc66-510d-11e7-8b9b-a872a53d05ff.png)

**Comment by Trim** [comment]
Hello,

I don't know what could happen here.
As I don't know how work the full code, it will be hard for me to suggest anything, sorry.

If you post the log written in your terminal, maybe we could find a hint.

Before posting log, be careful that ExchangeCalendar write a lot of informations and it would show some personal informations like URL, emails, .... Take a look into them, check that nothing personal is written and then only post here logs.

Thanks for the report :)

**Comment by pfps** [comment]
Yeah, I thought that it was a long shot that the solution is simple.  I don't see how Exchange Calendar can so badly interfere with the rest of thunderbird, but the problem only occurs when EC is active.  Maybe this is associated with the long startup times, which I'm also experiencing.

I'll try to cut down on the number of events in the calendar to see if the problem persists, and to cut down on the amount of information in the log.

**Comment by pfps** [comment]
I cleaned out a lot of event junk and restarted - same problem.
I created a new profile with only the Exchange calendar - everything works.  I added my work email to this profile - still working.
I went back to my old profile - works now!

Wierd.   I did one thing, though, which was to remove the manual sort extension, but I don't see how that affected things.

Anyway, I'll close this for now.
