### ISSUE TITLE
Unable to copy or click the meeting link in any meeting invitation

### ISSUE THREAD

**Issue by Gilwyad** [ExchangeCalendar/exchangecalendar#212]
I cannot copy or click the meeting invitation (Skype) link in any meeting invitation in my calendar because I get a 'JavaScript Application: Do not know how to handle this reference: https://' error.

Using 60.2.1 (64-bit) with v5.0.0-alpha1

**Comment by nparsons999** [comment]
I have the same problem. Before the TB update, I used to be able to click on the zoom or webex link and it would open. Now, I get the same error message. It's a minor inconvenience for me as I can cut/paste the the 'this reference error https://xxxxx link' and paste it into a firefox url bar and the conference call will open. It would be nice to have it working again but I think the dedicated engineers who got TB working again probably have more important things to work on. It's great that TB is working again as I really didn't want to start using ms office365 webmail again.

**Comment by pnad** [comment]
I waiting to review and merge.
Fix: https://github.com/ExchangeCalendar/exchangecalendar/pull/214

**Comment by Trim** [comment]
(sorry, PR 219 was intended for issue 203)

**Comment by rmainfo** [comment]
ExchangeCalendar:v5.0.0-alpha2 fixed this problem. Thanks!

**Comment by advancingu** [comment]
This appears to be fixed already.
