### ISSUE TITLE
Out of office settings: starts at/ends at date fields missing

### ISSUE THREAD

**Issue by bugwares** [ExchangeCalendar/exchangecalendar#215]
Hi!

At least in the German translation the date field entry boxed in the out of office settings are missing. The labels "Beginnt um" ("starts at") and "Endet um" ("ends at").

TB version 60.3
Plugin 5alpha1

**Comment by JohnSPeach** [comment]
I have the same problem
TB 60.3
I built it from the 5alpha2 branch (although the version still says alpha1).

**Comment by lucchinelli** [comment]
Hi,
I use the 5.0.0-alpha2 plugin in the version 60.3.3 and I have the same problem. There are texts but no time fields. You can set a hock for activating the time field but nothing happens.
![bug](https://user-images.githubusercontent.com/29096536/50338649-487b4100-0515-11e9-8fb7-53f313c93407.png)

**Comment by advancingu** [comment]
Should be fixed now.
