### ISSUE TITLE
Check server and mailbox does not work

### ISSUE THREAD

**Issue by gambr** [ExchangeCalendar/exchangecalendar#218]
Hi All,
I installed this add-on v 5.0.0.-alpha1 on thunderbird 60.3.1 (32 bit) but when I try to add a calendar and push on "check server and mailbox" button the "Next"  button remains disabled.
![image](https://user-images.githubusercontent.com/4397635/48540141-97500e00-e8b9-11e8-8647-525712f6b3bd.png)

Maybe this is fixed in 5.0.0-alpha2 but I didn't find how to download it.

Best regards,
Gianni

**Comment by zioalex** [comment]
Hi Gianni,
that version has been not yet released.
You have to clone the repo and switch to the branch 5.0.0-alpha2 and then build it.
`git clone https://github.com/ExchangeCalendar/exchangecalendar.git
cd exchangecalendar
git checkout v5.0.0-alpha2
make build`

Then you will find a new plugin in the same dir called exchangecalendar-v5.0.0-alpha1.xpi . Despite the name it is the correct one. Then install it manually.
Cheers

**Comment by gambr** [comment]
Thanks Alessandro,
but unfortunately I get the following error now after pushing "check server and mailbox"

![2018-11-15_12-34-33](https://user-images.githubusercontent.com/4397635/48550535-5533c600-e8d3-11e8-82f2-a08a263968e0.jpg)

I built it as you suggested, on a CentOS 6.3 64 bits. May be a problem if I use the .xpi file in a Thunderbird 32bits running on Windows 10?

**Comment by gambr** [comment]
Nobody?
