### ISSUE TITLE
Question: Transifex does not allow me to join the team to translate into Spanish and Galician

### ISSUE THREAD

**Issue by qosobrin** [ExchangeCalendar/exchangecalendar#224]
Back in the days when you moved the translation process to Transifex I requested the creation of translation teams for Spanish and Galician in your translation project. When these teams where created (I could see them in the list of languages, https://www.transifex.com/exchangecalendar/exchangecalendar/) I tried to join them with no luck; I could only join the language teams that had some translated.

I wonder if I am doing something wrong or maybe there is some sort of misconfiguration in these language teams.

Thank you very much. 
Regards.

**Comment by advancingu** [comment]
I just approved all translation membership requests, including yours. This should resolve this issue.
