### ISSUE TITLE
version 5 alpha 1

### ISSUE THREAD

**Issue by BGMcoder** [ExchangeCalendar/exchangecalendar#225]
In the alpha, there is an error fetching any exchange calendars.  These messages appear before the Thunderbird window begins to load.

I know this was an alpha release, but I was having troubles with version 4 in sychronizing calendars.  For some reason it would not save new events, and would often not display the existing events.  So I thought I'd try version 5.  I'm still running Thunderbird 52.9.1

![screenshot_thunderbird thunderbird _006](https://user-images.githubusercontent.com/1699670/49318179-26197900-f4bd-11e8-91e5-927513444b13.png)
![screenshot_thunderbird thunderbird _004](https://user-images.githubusercontent.com/1699670/49318186-2d408700-f4bd-11e8-9a5a-789a558cb952.png)
![screenshot_thunderbird thunderbird _005](https://user-images.githubusercontent.com/1699670/49318189-2f0a4a80-f4bd-11e8-8d33-a76c03e4f310.png)

**Comment by EqUaTe** [comment]
Version 5 requires TB60+ afaik.
alpha2 resolves most of the outstanding issues I had seen with that.

**Comment by advancingu** [comment]
Version 5 [only supports Thunderbird 60 and later](https://github.com/ExchangeCalendar/exchangecalendar/blob/v5.0.0-alpha3/install.rdf.template#L11), so even though it might not crash, running it in an earlier version can lead to unpredictable behavior.
Unfortunately we don't have the resources to support this old version of Thunderbird, so I'll have to close the issue.
