### ISSUE TITLE
ATN listing of ExchangeCalendar

### ISSUE THREAD

**Issue by ovari** [ExchangeCalendar/exchangecalendar#226]
Could you please advise where Exchange Calendar is listed on [ATN](https://addons.thunderbird.net/)?

Thank you

**Comment by advancingu** [comment]
This project is not listed at this time. Is there any specific requirement you have for a listing?

**Comment by ovari** [comment]
Some reasons that come to mind are:
1. Being able to find your wonderful add-on more easily.
2. Average Daily Users (ADU) statistics
3. When https://github.com/thundernest/addons-server/issues/4#issuecomment-444730010 is fixed, Download statistics

What do you think?

Thank you

**Comment by ovari** [comment]
4. You can also receive donations via the ATN website.

**Comment by ovari** [comment]
5. Can help people find your ExchangeCalendar add-on:
https://addons.thunderbird.net/addon/exquilla-exchange-web-services/reviews/1156248/
