### ISSUE TITLE
"Microsoft Exchange EWS: Password request." title shouldn't have a period

### ISSUE THREAD

**Issue by jsoref** [ExchangeCalendar/exchangecalendar#229]
![image](https://user-images.githubusercontent.com/2119212/49663488-d25ae280-fa1c-11e8-8a11-66eab172fa78.png)

Two basic thoughts:
1. Titles are not sentence like things and shouldn't include periods.
1. The title of a dialog shouldn't generally replicate content within a dialog (or conversely a dialog's content should repeat its title)

I suspect this is from https://github.com/ExchangeCalendar/exchangecalendar/blob/master/common/interface/exchangeAuthPrompt2/mivExchangeAuthPrompt2.js#L733

I'm running Thunderbird.app 60.3.3 (64-bit) w/ Exchange Calendar 5.0.0-alpha2

**Comment by advancingu** [comment]
@jsoref This was quite tough to figure out a proper solution. It turned out the entire string was hardcoded in English. Please check now.

**Comment by jsoref** [comment]
@advancingu : aww, but I gave you the pointer to the string!

That said, the PR looks good. (I'm unlikely to build my own package, although in a past life I would have, I'm bug reporting on behalf of someone else.)

**Comment by advancingu** [comment]
Merged.
