### ISSUE TITLE
Calendar with 4.0.0-beta2 fails to sync up completely

### ISSUE THREAD

**Issue by jlcenter** [ExchangeCalendar/exchangecalendar#23]
I just upgraded to TB v55.0b1 with Lightning 5.7 & my calendar fails to completely sync up with my Office365 calendar.  Both whole & partial days of appointments/events are missing.  I can see these events in Outlook.  Please let me know if there is anything I can do to help troubleshoot this.

**Comment by advancingu** [comment]
Did this work with the latest stable releases of Thunderbird and Lightning?

**Comment by poechtma** [comment]
I had similar or same problems with the latest versions of Thunderbird (52.2.0) and Lightning (5.4.2) and exchangecalendar-v3.8.0. I could connect to the exchange calendar but it was read only and the calendar entries were missing.
Upgrading the exchangecalender-Addon to 4.0.0-beta2 solved the problem for me.

**Comment by jlcenter** [comment]
I had to install the TB Beta PPA because the regular Ubuntu 16.04 release caused issues for me.  I've been using it for a while now.  I had to upgrade from exchangecalendar-v3.9.0 to the 4.0.0 betas because of issues with Office365.  I didn't notice this problem with the previous 4.0.0 beta, but I have a lot of appointments/events & I may have just missed it.  Now, whole days are blank, so hard not to notice that.

**Comment by Trim** [comment]
Hello,

I don't know who maintains the TB Beta PPA, but currently the TB Beta is version [54.0b3](https://www.mozilla.org/en-US/thunderbird/beta/notes/).

With this one (downloaded from Mozilla web site) and Debian Stretch it works well.

**Comment by advancingu** [comment]
Closing due to lack of actionable response.

**Comment by jlcenter** [comment]
FYI  - I removed the TB beta PPA & downgraded to v52.2.1, the Ubuntu stable version.  I also upgraded to EWS 4.0.0b4.  All of the calendar events/appointments reappeared.  So, something in the TB beta train was causing problems.  Thanks.  -John
