### ISSUE TITLE
v5.0.0-alpha3: Release note and version are not updated

### ISSUE THREAD

**Issue by fcand-sigfox** [ExchangeCalendar/exchangecalendar#233]
CHANGELOG.md is not updated.
VERSION is not updated either.

**Comment by advancingu** [comment]
Yeah, since there is no v5.0.0-alpha3 release yet.

**Comment by fcand-sigfox** [comment]
Sorry my mistake I thought I was on a tag, did not notice I was just on a branch.

**Comment by advancingu** [comment]
No problem. :+1:
