### ISSUE TITLE
 Merge gl (Galician) locale translations from Transifex

### ISSUE THREAD

**Issue by ovari** [ExchangeCalendar/exchangecalendar#235]
Please merge the gl (Galician) translation from Transifex. Thank you

**Comment by advancingu** [comment]
@ovari Thanks, please try this test build: [exchangecalendar-v5.0.0-alpha2.zip](https://github.com/ExchangeCalendar/exchangecalendar/files/2757260/exchangecalendar-v5.0.0-alpha2.zip)

**Comment by ovari** [comment]
Suggestion:
Sort translators in `install.rdf` in locale order
```
        <em:translator>Christian A. Meyer (de)</em:translator>
        <em:translator>Björn Töpper (de)</em:translator>
        <em:translator>Michel Verbraak (en-US)</em:translator>
        <em:translator>Dominique Fillon (fr-FR)</em:translator>
        <em:translator>Óvári (hu)</em:translator>
        <em:translator>Alessandro Menti (it-IT)</em:translator>
        <em:translator>Hiroshi Miura (ja-JP)</em:translator>
        <em:translator>Michel Verbraak (nl)</em:translator>
        <em:translator>Alexey Sinitsyn (ru)</em:translator>
        <em:translator>Engin Özkan (tr)</em:translator>
```

What do you think?

**Comment by ovari** [comment]
Are you also able to add the name of the translator for the `gl` locale to `install.rdf`?

**Comment by ovari** [comment]
Can you leave a comment on Transifex for the gl translator to check https://github.com/ExchangeCalendar/exchangecalendar/issues/235#issuecomment-454181817? Unfortunately, we don't know Galician. Thank you

**Comment by ovari** [comment]
Can you please advise when the [gl](https://github.com/ExchangeCalendar/exchangecalendar/issues/235) and [hu](https://github.com/ExchangeCalendar/exchangecalendar/issues/234) locales will be merged into the [master](https://github.com/ExchangeCalendar/exchangecalendar) branch? Thank you

**Comment by advancingu** [comment]
Merged.

**Comment by advancingu** [comment]
@ovari I updated `install.rdf` as suggested. Merging to `master` will not take place for some time since `master` must be a known working version. Right now this is going into version 5 alphas.

**Comment by qosobrin** [comment]
Hi, there:

could you add my credits for the translation into Galician and Spanish? My name is Luis A. Martínez

Thank you. 
Regards,
