### ISSUE TITLE
ExchangeCalendar version numbers to follow supported Thunderbird ESR version numbering

### ISSUE THREAD

**Issue by ovari** [ExchangeCalendar/exchangecalendar#236]
Suggestion:
[Release](https://github.com/ExchangeCalendar/exchangecalendar/releases) the next version of ExchangeCalendar in the format of `60.4.zzzz`. This includes the next alpha version, if there is one. Thunderbird ESR is currently `60.4.0` so ExchangeCalendar version would be `60.4.zzzz`, where `zzzz` is the version number of your ExchangeCalendar add-on.

For example, see [ExQuilla for Microsoft Exchange Version History](https://addons.thunderbird.net/addon/exquilla-exchange-web-services/versions/). A excerpt is shown in the image below:

![ExQuilla for Microsoft Exchange Version History](https://user-images.githubusercontent.com/17465872/50386909-354eb800-0745-11e9-8340-7eb07e870338.png)

It would help users know which version of Thunderbird your add-on supports. https://github.com/ExchangeCalendar/exchangecalendar/issues/225

What do you think?

Thank you

**Comment by wagner-certat** [comment]
But one Addon version can support multiple TB versions?

**Comment by ovari** [comment]
It was based on the release notes of https://github.com/ExchangeCalendar/exchangecalendar/releases/tag/v5.0.0-alpha1

> Added
> * Initial support for Thunderbird 60
> 
> Removed
> * Support for Thunderbird 59 and lower

**Comment by Trim** [comment]
> But one Addon version can support multiple TB versions?

Yes it could, but that's a nightmare for extensions with low activity such Exchange Calendar.

Especially for Exchange Calendar which has requirements on Thunderbird and Lightning versions and both are having a lot of breaking changes on each new release.

**Comment by ovari** [comment]
@advancingu can `ExchangeCalendar 5.0-alpha3` be renamed to `ExchangeCalendar 60.0-alpha3`?

**Comment by advancingu** [comment]
Version compatibility is defined in https://github.com/ExchangeCalendar/exchangecalendar/blob/master/install.rdf.template so I don't see how creating an external dependency (even if only administrative) is of any help. If anything, the next step would be to get listed in the Add-on registry again so that updates can be pushed automatically. Then there is no need to worry about getting the right version.
