### ISSUE TITLE
Special Characters (German)

### ISSUE THREAD

**Issue by paul4haren** [ExchangeCalendar/exchangecalendar#24]
When making a new appointment in Lightning, the special german characters disappear, an are replaced by questionmaks.
When syncing new appointments from the server, the special german characters  remain unchanged.

**Comment by advancingu** [comment]
I can't reproduce this (see screenshot). Which version are you using?

![screenshot from 2017-06-19 21-21-07](https://user-images.githubusercontent.com/130207/27301920-4766c276-5535-11e7-81ab-e81bcaed9627.png)

**Comment by paul4haren** [comment]
Thank you for for answering so quickly.
I'm using Thunderbird 52.1.0 (64-Bit) on a german instalation of OpenSuse
Leap 42.1 and 42.2
with ews provider 4 beta2.
The problem existed on 3.9 also...
yours
PB

2017-06-19 21:21 GMT+02:00 Markus Weiland <notifications@github.com>:
