### ISSUE TITLE
Some strings are not localized

### ISSUE THREAD

**Issue by advancingu** [ExchangeCalendar/exchangecalendar#240]
Expected:
* The following strings shall be translated:
  * `Exchange Contact Settings` window
    * Title
    * Server URL label
  * `Microsoft Exchange EWS: Password request.` window title

https://user-images.githubusercontent.com/17465872/51069853-39f2f600-168b-11e9-8abd-c37c590b2b08.png

https://user-images.githubusercontent.com/17465872/51071540-a0394200-16a6-11e9-9702-656ae93dd890.png

Extracted from #234.

**Comment by ovari** [comment]
Can these please be translated too (en → hu):
https://ews.example.com/ews/exchange.asmx → https://ews.példa.hu/ews/exchange.asmx
yourname@example.com → a.neved@példa.hu

**Comment by Trim** [comment]
Hello,

The [example.com](http://example.com) domain is a standard reserved domain to be used as examples. And so this domain will never be sold and used by anyone.

I understand that's not really good as it's not translated, but http://példa.hu/ (and others in other languages) is not a reserved domain and so we shouldn't use it as it can send user to a bad servers (like website with malwares, illegal content...).

**Comment by advancingu** [comment]
Good points @Trim, I agree to keep @example.com in this case.

**Comment by ovari** [comment]
Good point @Trim and agree to keep [example.com](https://en.wikipedia.org/wiki/Example.com) where there is currently no localized reserved domain.

1. For hu locale, can `yourname` be translated to become:
yourname@example.com → a.neved@example.com

2. Perhaps for the en locale, it could be:
yourname@example.com → your.name@example.com

3. Where there is localized reserved domains for [example.com](https://en.wikipedia.org/wiki/Example.com), can [example.com](https://en.wikipedia.org/wiki/Example.com) be translated:

Domain | Domain (A-label) | Language | Script
-- | -- | -- | --
إختبار | XN--KGBECHTV | Arabic | Arabic
آزمایشی | XN--HGBK6AJ7F53BBA | Persian | Arabic
测试 | XN--0ZWM56D | Chinese | Han (Simplified variant)
測試 | XN--G6W251D | Chinese | Han (Traditional variant)
испытание | XN--80AKHBYKNJ4F | Russian | Cyrillic
परीक्षा | XN--11B5BS3A9AJ6G | Hindi | Devanagari (Nagari)
δοκιμή | XN--JXALPDLP | Greek, Modern (1453-) | Greek
테스트 | XN--9T4B11YI5A | Korean | Hangul (Hangŭl, Hangeul)
טעסט | XN--DEBA0AD | Yiddish | Hebrew
テスト | XN--ZCKZAH | Japanese | Katakana
பரிட்சை | XN--HLCJ6AYA9ESC7A | Tamil | Tamil

https://www.iana.org/domains/reserved

What do you think?

Thank you

**Comment by advancingu** [comment]
@ovari I've decided not to localize the URLs for now as  it is hard to assert that the domain is not modified by a translator.

**Comment by advancingu** [comment]
Merged.

**Comment by ovari** [comment]
Thank you @advancingu. When should we update the hu strings? Thank you once again.

**Comment by advancingu** [comment]
@ovari Whenever you want. When you are done, open an issue so that I know when to merge.

**Comment by ovari** [comment]
All the Hungarian strings should be translated on Transifex. Can you please import them? Thank you

**Comment by ovari** [comment]
Can the beginning of the email please be translated?
`yourname@example.com` → `a.neved@example.com`
