### ISSUE TITLE
"Primary email address" field in "Create New Calendar" dialog should be stretchable

### ISSUE THREAD

**Issue by logological** [ExchangeCalendar/exchangecalendar#244]
In the "Create New Calendar" dialog, almost all the input fields dynamically resize to fit the width of the window whenever the window itself is resized.  The only exception is the "Primary email address" field, whose width is fixed (and incidentally, too narrow to fit many common e-mail addresses).  This field should also be configured to stretch and shrink along with the window.

Possibly related to Issue #59.

**Comment by advancingu** [comment]
Should be fixed with #241.
