### ISSUE TITLE
Office365 multi factor authentication

### ISSUE THREAD

**Issue by jgato** [ExchangeCalendar/exchangecalendar#247]
Hi,

do you intend to add support to multi factor authentication? The enterprise account I am using is including now 2 factors authentication, first one emails+password and second one a PKI. 

Davmail has included that recently:
https://sourceforge.net/p/davmail/feature-requests/111/
great to read emails and calendar. By the calendar does not work very well in my case, with some synchronization issues. I had very good times using your addon, but I had to put it away when the MFA appeared. Do you think you could support it?

Many thanks,

**Comment by mtbc** [comment]
Did you see #47?

**Comment by jgato** [comment]
sorry :(
