### ISSUE TITLE
New alpha release?

### ISSUE THREAD

**Issue by mrueg** [ExchangeCalendar/exchangecalendar#248]
https://github.com/ExchangeCalendar/exchangecalendar/compare/v5.0.0-alpha2...v5.0.0-alpha3 shows a bunch of changes that might be useful to test.

**Comment by advancingu** [comment]
[Done](https://github.com/ExchangeCalendar/exchangecalendar/releases/tag/v5.0.0-alpha3).

**Comment by mrueg** [comment]
thanks!
