### ISSUE TITLE
Cleanup old configuration

### ISSUE THREAD

**Issue by Trapulo** [ExchangeCalendar/exchangecalendar#249]
Hi,
every time I open TB, the plugin asks my for a password related to an account (and calendar) I've deleted. I removed the calendar from TB, etc etc but still it asks for the password. Where are accounts saved? How can I remove the orphan reference?

thanks

**Comment by advancingu** [comment]
Could you try reinstalling the add-on? That should flush any remaining data.

**Comment by Trapulo** [comment]
If I uninstall it, all ok.
If I reinstall it, the problem come back! :(

**Comment by sebix** [comment]
> If I uninstall it, all ok.
> If I reinstall it, the problem come back! :(

Did you restart thunderbird inbetween?

**Comment by Trapulo** [comment]
sure

**Comment by advancingu** [comment]
The only other suggestion I have is to try to delete your entire exchangecalendar configuration. From what I can tell that should be the folder `exchange-data` in your Thunderbird profile folder (usually located in `~/.thunderbird/` under Linux).

**Comment by ontheair81** [comment]
Having the same issue. Uninstalling and reinstalling the plugin: Same effect.
Even after deleting the folder "exchange-data" and reinstalling the plugin: There is always the popup for a password for a very old account.

Would be great to know where these settings are stored to delete an old configuration!

**Comment by Trapulo** [comment]
I solved checking how source code works.
Account are saved in TB preferences framework. Values are accessible via tools -> options . You can find and delete keys related to old account.
