### ISSUE TITLE
Adding a calendar fails when the given name contains special characters on Windows

### ISSUE THREAD

**Issue by huljar** [ExchangeCalendar/exchangecalendar#262]
I have tried adding my personal calendar from the hosted exchange of my organization. However, when I gave it a name containing a German umlaut ('ö' in this case), adding the calendar after completing the wizard failed with the following error message:

![error](https://user-images.githubusercontent.com/24304044/53947465-16b25900-40c6-11e9-8a98-e782ed5b3ef2.png)
*roughly says: An error occurred while adding the calendar with address ... It will not be available.*

When I replaced the 'ö' with 'oe', everything worked fine.

* TB version: 60.5.3
* Lightning version: 6.2.5.3
* ExchangeCalendar version: 5.0.0-alpha3
* OS: Windows 10

I remember doing the same thing on Linux (Debian stable) and this problem did not occur; using 'ö' worked fine.

**Comment by advancingu** [comment]
@huljar Please check if the changes in #279 fix this issue.

**Comment by huljar** [comment]
I can confirm that #279 fixed the issue for me. It's working perfectly now! Currently using TB 60.7.0 and Lightning 6.2.7.
