### ISSUE TITLE
Please pull my latest French translation update from Transifex

### ISSUE THREAD

**Issue by DevDef** [ExchangeCalendar/exchangecalendar#266]
Hi,

I’ve just done a complete review of ExchangeCalendar French translation strings (lots of fixes, including better respect of orthotypographic rules: true apostrophes, French guillemets, non-breaking spaces before colons, thin spaces before question and exclamations marks, etc.).
Unfortunately, I haven’t found a way to download the translation from Transifex to build my own XPI. :-(
Could you please pull the French translation from Transifex and merge it in the v5.0.0-beta1 branch?

TIA,

Davy

**Comment by DevDef** [comment]
Finally, I managed to fetch my translation from Transifex with the tx command line client, and then rebuild an xpi file.
Anyway, an update would be nice…

**Comment by advancingu** [comment]
I pulled all translations in #275. Thanks.
