### ISSUE TITLE
Tasks not Working in TB60 with Alpha v3

### ISSUE THREAD

**Issue by ttjaden** [ExchangeCalendar/exchangecalendar#269]
Linux Mint 19
Thunderbird 60.6.1
ExchangeCalendar 5.0.2 and 5.0.3

Problem: It's not possible to create tasks. Calendar is shown and Calendar entries are possible but it's not possible to see or create tasks in this calendar. 

Is this a known issue?

**Comment by Champal** [comment]
You have to add the same account but with another directory.

![image](https://user-images.githubusercontent.com/3206590/61892030-3af2c300-af0b-11e9-97c5-a0a8e3db8e7c.png)
