### ISSUE TITLE
No calendar with thunderbird 60.6.1 + Lightning 6.2.6.1 + Exchange Calendar v5.0.0-alpha3

### ISSUE THREAD

**Issue by attila123** [ExchangeCalendar/exchangecalendar#270]
Hi, my thunderbird was updated to 60.6.1 and since then there is no calendar (disabled).
I am not sure if this is an issue with this addon or with TB + Lightning.
As mentioned in the title I have the following components now:
thunderbird 60.6.1 + Lightning 6.2.6.1 + Exchange Calendar v5.0.0-alpha3.
Unfortunately I do not know what was the previous, working Thunderbird version.
Reported the issue aslo to https://support.mozilla.org/en-US/questions/1254946, did not get any reply.
I also tried to rename my storage.sdb (as per http://forums.mozillazine.org/viewtopic.php?f=46&t=596262) and re-add my calendar but still does not work.

**Comment by EricV** [comment]
Works for me but with exactly the same versions on debian...

**Comment by elhennig** [comment]
I also have TB 60.6.1 with Lightning 6.2.6.1 and th Exchage Provider 5.00 alpha3 on opensuse Leap 15.0 and for me office365 calendars work fine so far

**Comment by attila123** [comment]
@EricV @elhennig Thanks for the confirmation! Finally I created a new thunderbird profile (exit thunderbird then `thunderbird --ProfileManager`), set up my email account and calendar, and now it works. So closing issue.
