### ISSUE TITLE
Task HTML editor is stuck some times

### ISSUE THREAD

**Issue by Trim** [ExchangeCalendar/exchangecalendar#28]
While trying to resolve issue #5 , we reached multiple different issues.

Most have been able to be fixed, but [one remains](https://github.com/ExchangeCalendar/exchangecalendar/issues/5#issuecomment-308723206). To be more clear about the current status (4.00beta3) of releases, I open a new issue here.

As mentioned before, I've made [some tries to fix this one](https://github.com/Trim/exchangecalendar/tree/wip-fix-html-editor), but I'm not able to resolve it and I think I've reached the point where I have not enough knowledge on Javascript and XUL technologies to be able to understand and fix the issue.

Note, that as I never used before the exchangecalendar task editors, I don't know the previous state of this element: does it was full working, does it had already some bugs ?

## Current issue description

Exchangecalendar task editor provides a HTML text editor based on the `<editor>` XUL element.

[I've found on the web](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/editor) that Mozilla don't provide a simple HTML editor directly but requires every project needing this to create themself a binding between the text area (the `editor`) and required buttons (like `bold`, `italic`, ...).

So, the exchangecalendar plugin does the right thing by defining itself a `<exchWebServiceEditor>` XBL element which contains the required `editor` text area, `toolbar` and the JavaScript bindings between them.

The issue is that, _sometimes_, the HTML editor is stuck in an unusable state: italic, bold and underlined buttons are stuck in an active state and the textarea is unable to be selected:

![blocked editor screenshot](https://user-images.githubusercontent.com/6523034/27025641-8097162a-4f5b-11e7-9fda-5928defd764f.png)

For me, it doesn't always appear, but for @smvicente it appears 98% of the time.

What I've discovered is that this state correspond to an exception raised when a click event happens. The exception is raised when the JavaScript code try to create an instance (in the XUL world) of `nsICommandParams` to read some button state.

The strange part is that it works well for say 5 buttons, but it fails on the `ol_command` button. I've tried to `try/catch` this exception to allow the code continues its execution, but then it failed with another instantiation creation in other part of the code.

## Some tries / suggestion which didn't work

As suggested by @advancigu it can be an error of general initialization of the editor as it apperas only some times and on some basic XUL feature.

I've tried to get rid of `<constructor>` and `<destructor>` of the XBL element, but it seems to not work correctly if event handlers aren't loaded on XBL constructor phase.

Now I remember that this issue appeared after I've fixed another issue in the HTML editor: before I work on this code, the task editor reached an XML exception because the task editor dialog tried to insert badly formed HTML content inside the HTML editor. To fix this issue, I took the decision to modify the content setter to force the content to be inserted to be fixed by the Mozilla DOM parser. So, I think there is two options: either this fix caused the new issue, or this issue have always existed but wasn't reachable because of the XML parsing issue.

**Comment by smvicente** [comment]
Thank you for all the effort once again @Trim !

After trying out the beta3 going to describe better what I see, just in case it helps.

So, some times, the task description content is displayed correctly and I can update it without a hassle but, most of the times, when opening the tasks, I get to see the content briefly, but gets overwritten by a blank page immediately. If I don't hit save when that happens is ok and nothing changes, but if I save it, it will be get overwritten by the "blank" page, erasing any previous content. 

When the HTML editor gets blocked, the fact that I get to see the task's content briefly makes me think could be related to some race condition, but of course is just an idea as I have no idea about the internals :(

In any case, I'm very grateful with you for fixing most of the problems!

Best.

**Comment by advancingu** [comment]
@rkent Do you know anyone in the Thunderbird or Lightning teams who could help us troubleshoot?

**Comment by rkent** [comment]
No, I can't suggest anyone.

**Comment by Trim** [comment]
Well, I found a really good hint inside the "Rapid Application Development with Mozilla" book by Nigel McFarlane (available in a comment of this [article](https://lwn.net/Articles/141453/)).

In XBL chapter, I've noticed this paragraph:

> ### 15.2.1 Bound Tags and -moz-binding
>Most, but not all, XUL and HTML tags can be bound to an XBL binding. For a
>tag to be bound, it must have a frame—a styleable rectangular area in which
>it is displayed.
>Any tag with this style has no frame and cannot be bound:
> ```css
>{ display: none; }
>```
>A tag that gains this style will lose any binding that it has. For this rea-
>son, a bound XUL tag **should be collapsed rather than hidden** if it needs to be
>visually suppressed.

I've check modifications I've made when porting the item dialog to the new iframe style and I've found I settled by default `hidden=false` inside the XUL definition and that wasn't the case before.

So I've updated the XUL and the JavaScript code to use the collapsed attribute instead.

It seems to work for me now, but I suggest to do a new beta with my todays pull requests (one is coming) to have more tests.

**Comment by smvicente** [comment]
@Trim ! that sounds great!! I can test it in the moment the new beta is released of course!

**Comment by advancingu** [comment]
Should be fixed now.

**Comment by smvicente** [comment]
Hi guys! there is no release available yet to test this out right?

Thanks a million.

**Comment by smvicente** [comment]
Hi guys! there is no release available yet to test this out right?

Thanks a million.

**Comment by smvicente** [comment]
Guys! Can confirm this issue is well fixed!

I'm not sure how to thank you for all the effort. Please let me know where I can donate.
