### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by naevtamarkus** [ExchangeCalendar/exchangecalendar#289]
Hi,
I just wanted to ask if this project is still alive, since it's been several months I don't see activity and we're in Alpha since almost a year.
I'm using the old version still (had to lock Thunderbird updates) and was thinking about jumping in when you release the Beta... but I wonder if that's even a good idea at this point.
Thanks a lot, I hope you don't mind me asking.

**Comment by advancingu** [comment]
Yes (with caveats). I've been tied down with projects that fully support me financially in the past months, so progress has simply been very slow.

The current Alpha release worked well enough for my use cases, so feel free to give it a try.
