### ISSUE TITLE
Can't update events descriptions

### ISSUE THREAD

**Issue by smvicente** [ExchangeCalendar/exchangecalendar#29]
Since the update to Thunderbird 52.1.1, Lightning 5.4 and EWS Provider v4.0.0-beta3, I can not update event's descriptions from Lightning calendar as before, as they get always overwritten with the one in the server right after saving.

Creation of the event if fine, is just when trying to update the description inside the event after being created.

A similar problem was happening when updating task's descriptions, but that was already fixed in #5.

Best.

**Comment by Trim** [comment]
Thanks for your feedback 👍

**Comment by advancingu** [comment]
Should be fixed now.

**Comment by smvicente** [comment]
I can also confirm this issue is well fixed!!
