### ISSUE TITLE
not compatible with thunderbird 68

### ISSUE THREAD

**Issue by Mikki-black** [ExchangeCalendar/exchangecalendar#296]
The latest version v5.0.0-beta1 doesn't seem to be compatible with thunderbird 68 and fails to install.

**Comment by Mikki-black** [comment]
duplicate...

**Comment by elhennig** [comment]
If you have a look at the existing issues (especially #277) you will se that this is already well known and work is in progress. There is no way to use the addon with TB 68+ so if you rely on it you will probably have to downgrade to 60.X
