### ISSUE TITLE
Not compatible with Thunderbird 68+ -> New release ?

### ISSUE THREAD

**Issue by maat-github** [ExchangeCalendar/exchangecalendar#298]
Hello,

Everything is in the title... The Exchange Calendar Provider stopped working with last update of Thunderbird...

Would it be complex to release a new version that works with TB68+ ?

By the way congrats for the job you do with this add-on

Best regards,
M

**Comment by wagner-certat** [comment]
Duplicate of #277

**Comment by maat-github** [comment]
Opps sorry i should have controlled better :-(
I close my issue and will follow the #277 
Thank you for your comment
M
