### ISSUE TITLE
No longer working on 68.1.0

### ISSUE THREAD

**Issue by kiravi** [ExchangeCalendar/exchangecalendar#302]
Tried everything, such as removing compatibility checks etc.

**Comment by ric-cz** [comment]
Yes, the same here. TB 68.1 x64 Win10. Please update it for newer TB.

**Comment by bren-m** [comment]
Same as #277

**Comment by Trapulo** [comment]
same 68.1.1 with 5.0.beta1

**Comment by elhennig** [comment]
Still the same as  #277
