### ISSUE TITLE
Add another user's shared calendar

### ISSUE THREAD

**Issue by tshaw-ic** [ExchangeCalendar/exchangecalendar#303]
My office uses O365 for email and calendar. I'm running Thunderbird 60.8.0 and Exchange Calendar 5.0.0-beta1. I was able to add my Outlook calendar to Thunderbird without issue, but I can't figure out how to add our shared calendar. As far as I can tell, the shared calendar is another user's primary or secondary calendar which they have shared access to with everyone else; I can't find it any shared folder of the server. The email inviting me to share this calendar had a file attached called "sharing_metadata.xml" which I've removed some personal information from and converted to .txt so I can upload it here. The all-caps strings are the redacted information. I'm hoping someone can figure out how I can find the shared calendar from this file.
[sharing_metadata_santized.txt](https://github.com/ExchangeCalendar/exchangecalendar/files/3648906/sharing_metadata_santized.txt)

**Comment by bberndt** [comment]
I haven't done this in years, but did find some very basic notes I made for myself...  See if it works for you. 

1. add new calendar, on the network, and exchange compatible. 
2. use https://[FQDN of exhange web access]/ews/exchange.asmx fpr the network calendar server
3. primary email address= email of shared calendar user.
5. username = your user name
6. domain = [(active directory) domain]
7. share folder ID FolderId hex number from xml file invite

**Comment by tshaw-ic** [comment]
That's perfect, thank you so much!

For anyone else reading this, the URL in step 2 is the same as the URL I used to add my own Outlook calendar. For O365, that's https://outlook.office365.com/ews/exchange.asmx
