### ISSUE TITLE
68.1.1 on Linux breaks 5.0.0-beta1

### ISSUE THREAD

**Issue by rkoktan** [ExchangeCalendar/exchangecalendar#305]
I just had TB 68.1.1 pushed to me and it breaks 5.0.0-beta1... "Exchange Calendar is incompatible with Thunderbird 68.1.1"... any chance there is a quick fix?

Thanks,
Rob

**Comment by Oskar1983** [comment]
Duplicate of #277

**Comment by gdraheim** [comment]
It's Opensuse 15.1 in my case.
