### ISSUE TITLE
Build compatible with Tunderbird 68 ?

### ISSUE THREAD

**Issue by AnthonyBarbier** [ExchangeCalendar/exchangecalendar#307]
Hi,

Would it please be possible to have a `xpi` build compatible with Thunderbird 68 ? (The current beta isn't).

Thanks

**Comment by elhennig** [comment]
see #277

**Comment by NickETH** [comment]
Hi folks,
for the impatient around us (and advanced...), there is a way.
Just select the "277-thunderbird-67-compatibility" and clone it.
Then remove the unnessary stuff and zip it. rename the extension to xpi.
That's all.
BR, Nick

**Comment by sleeksorrow** [comment]
This branch is work in progress and does NOT give you a working plugin. See https://github.com/ExchangeCalendar/exchangecalendar/pull/304#issuecomment-538945089

Please don't send people after red herrings.
