### ISSUE TITLE
Exchange Calendar is incompatible with Thunderbird 68.2.2

### ISSUE THREAD

**Issue by tkoeck** [ExchangeCalendar/exchangecalendar#308]
AS shown in the screenshot from Debian 10 it seems to be incompatible with TB 68.2.2
![Screenshot from 2019-11-19 10-48-06](https://user-images.githubusercontent.com/42435353/69140275-7882e980-0ac2-11ea-85d6-0e572b938d9f.png)

**Comment by elhennig** [comment]
See #277

**Comment by larskanis** [comment]
I have donated $15 on BountySource.com for resolving this issue: https://www.bountysource.com/issues/84017522-exchange-calendar-is-incompatible-with-thunderbird-68-2-2

**Comment by sleeksorrow** [comment]
Thank you f or pointing this out and for donating.  Just a bit sad that the bounty is pointing to this duplicate instead of the correct issue #277.

**Comment by advancingu** [comment]
Already reported in #277.

**Comment by advancingu** [comment]
Reopening as the bounty is linked here. Let's hope it also reopens the bounty.

**Comment by advancingu** [comment]
Looks like the bounty does not reopen. Keeping this issue closed then.

@larskanis If possible, you should migrate the bounty to #277.

**Comment by larskanis** [comment]
@advancingu I requested a transfer of the bounties to #277. I'll let you know when it's done.

**Comment by larskanis** [comment]
Financial bounties have been transferred to the correct issue #277 now: https://www.bountysource.com/issues/74122217-compatibility-with-thunderbird-67-and-newer-versions

I also opened a PR to update the link in the README: #314
