### ISSUE TITLE
Thunderbird 68.4.1 update broke v5.0.0-beta1

### ISSUE THREAD

**Issue by SergeLalonde** [ExchangeCalendar/exchangecalendar#311]
The title says it all.
This add-on is fantastic and I hope that fixing it won't take too long.

To avoid this issue in the future, I'll be submitting a suggestion to Thunderbird developers to check add-on compatibility before upgrading so that users can delay the upgrade if an important add-on is no longer compatible.

Thanks for the great work!

**Comment by SergeLalonde** [comment]
Someone beat me to it:
https://bugzilla.mozilla.org/show_bug.cgi?id=1531786

**Comment by camelcamro** [comment]
well, for worst case, you can test to disable the explicit check ...
see:
https://www.ghacks.net/2018/04/24/thunderbird-60-and-extensions-support/
(is only a workaround for now)

**Comment by SergeLalonde** [comment]
@camelcamro Thanks for the suggestion, but unfortunately it didn't work. The extension was enabled, but it didn't work properly and corrupted the link to the Exchange Calendar and the add network calendar dialog was no longer modified by the add-on.
It was worth a try though!

**Comment by sleeksorrow** [comment]
See #277

**Comment by advancingu** [comment]
Already reported in #277.
