### ISSUE TITLE
Error file corrupt, cant install in the latest thunderbird.

### ISSUE THREAD

**Issue by aTGuz** [ExchangeCalendar/exchangecalendar#316]
When I try to install, the v5 or v4 thunderbird shows an error telling that the file seems to be corrupt.

![image](https://user-images.githubusercontent.com/5741150/130489424-0d90d7ba-63a6-4727-bdc9-01a9ca01229d.png)

**Comment by josecale** [comment]
Please note that version 5 only supports Thunderbird 60.
If you are using a current version of Thunderbird this extension will not suit you -- it was not updated to support current versions of Thunderbird.

**Comment by advancingu** [comment]
See https://github.com/ExchangeCalendar/exchangecalendar/issues/277
