### ISSUE TITLE
English copy-editing

### ISSUE THREAD

**Issue by logological** [ExchangeCalendar/exchangecalendar#32]
Much of the English-language text in the project (documentation, user-facing strings, etc.) is full of spelling and grammar errors or is awkwardly or inconsistently worded.  (Even the project's name in the README doesn't match the name of the add-on as registered with Thunderbird!)

I can probably do some cleanup here and will submit some pull requests referencing this issue.

**Comment by advancingu** [comment]
Merged #33.
