### ISSUE TITLE
Gotchas and incompatibilities in build script

### ISSUE THREAD

**Issue by logological** [ExchangeCalendar/exchangecalendar#38]
The `build.sh` script is not written in a way that will work with all Bourne-compatible shells, and uses globbing in dangerous ways.  In particular:

* Commands such as `echo "-u:enable update"` can be misinterpreted as passing a command-line parameter to `echo`
* Globbing in lines such as `zip -r exchangecalendar-v$version.xpi * …` could end up passing command-line parameters to `zip` if there exist filenames starting with a hyphen
* Variable substitution in lines such as `zip -r exchangecalendar-v$version.xpi …` could result in unwanted word splitting, depending on the value of `$version`.

**Comment by advancingu** [comment]
Merged.
