### ISSUE TITLE
Gotchas and incompatibilities in translationupdater.sh

### ISSUE THREAD

**Issue by logological** [ExchangeCalendar/exchangecalendar#40]
The `translationupdater.sh` script employs some semantically questionable, inelegant, and even dangerous constructs, particularly with relation to globbing and quoting.  (See for the example the output of [ShellCheck](https://www.shellcheck.net/), a lint-like tool for Bourne-compatible shell scripts.)  The code should be cleaned up to prevent gotchas and incompatibilities.

See also Issue #38.

**Comment by advancingu** [comment]
Resolved in `4.0.0-beta4`. Thanks.
