### ISSUE TITLE
O365 2FA support?

### ISSUE THREAD

**Issue by BenjamenMeyer** [ExchangeCalendar/exchangecalendar#47]
Any chance of getting O365 2-factor auth support? (outside of the Application Password functionality which would already be supported)

**Comment by Trim** [comment]
I don't think so, because currently there are few developers and it will need to have access to office 365 with 2-factor authentication enabled.

Furthermore, current authentication process relies on Thunderbird code which make almost all the job to authenticate user (by using standard Basic/NTLM authentication through XML HTTP requests).

**Comment by advancingu** [comment]
Thank you for the feature suggestion. Unfortunately I'll have to close this as out of scope. This is far beyond the resources we currently have available.

**Comment by msangel** [comment]
More and more mail providers start using 2FA. This should be at least in todo list.

**Comment by fbicknel** [comment]
So... In the future when all mail platforms use mfa, where will TB be?

**Comment by BenjamenMeyer** [comment]
Q: Has anyone filed a bug with Thunderbird proper to do 2FA? I'm thinking of doing so.

**Comment by BenjamenMeyer** [comment]
NOTE: Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1528136 and found https://bugzilla.mozilla.org/show_bug.cgi?id=1427538; Thunderbird folks may not want to do this. Perhaps if folks could join in and discuss a plugin architecture to do it that might help get a workable solution through. Not sure - just a thought.

**Comment by BenjamenMeyer** [comment]
Please re-open to track the the Mozilla bug as this is not really resolved.

**Comment by jgato** [comment]
Any progress about this?

**Comment by BenjamenMeyer** [comment]
As I'm changing jobs, I don't have an O365 account that needs this right now - I do expect that'll change so I'm still quite interested in seeing this through; it's just harder for me to provide direct insight and support of the bug tracker.

So if anyone can comment on the Mozilla bug I filed - https://bugzilla.mozilla.org/show_bug.cgi?id=1528136 - we might be able to make some traction with the Thunderbird team in at least getting that bug report verified and properly classified in their system. With enough folks reporting hopefully we can garnish enough attention to get something addressed too.

**Comment by elhennig** [comment]
I heared from our IT that EWS (and IMAP) will be switched off October 2020 by MS. I guess if that is true the topic becomes relevant then again.

**Comment by aleksandrs-ledovskis** [comment]
> Basic Authentication for Exchange Web Services (EWS) will be retired, beginning October 13, 2020, as we focus our efforts on OAuth 2.0.

No mention of IMAP decomissioning.

Ref: https://blogs.technet.microsoft.com/skywriter/2017/08/07/office-365-planned-service-changes-2020/

**Comment by elhennig** [comment]
Thanks for the pointer. If it is only basic auth I hope that TB and the EWS addon both support OAuth 2.0 until then

**Comment by elhennig** [comment]
I found this https://techcommunity.microsoft.com/t5/Exchange-Team-Blog/Improving-Security-Together/ba-p/805892
Here it is clearly stated that the change to switch off basic auth also affects IMAP amongst other services.

**Comment by BenjamenMeyer** [comment]
Just FYI - the Thunderbird team seems to be taking up my bug ticket (https://bugzilla.mozilla.org/show_bug.cgi?id=1528136). There's been a lot of interest around it in the last month, and seems like there will be a resolution in the not too distant future (per https://bugzilla.mozilla.org/show_bug.cgi?id=1528136#c32).

Depending on how they resolve that there may be the ability to do any 2FA or just O365's 2FA; not sure. I ended up asking for a framework for auth plugins so the community could contribute modules for doing auth and then migrating existing auth mechanisms into that framework. We'll see what happens.

**Comment by mtbc** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1528136 seems to be,
> Status: RESOLVED FIXED
> Milestone: Thunderbird 77.0

**Comment by BenjamenMeyer** [comment]
Yes, they've been working on OAUTH2 support with O365.
