### ISSUE TITLE
How do I use the addon after it is installed?

### ISSUE THREAD

**Issue by digulla** [ExchangeCalendar/exchangecalendar#50]
How do I configure the EWS server to use?
Where do I specify user/password?
How do I sync my calendars?

I'm using TB 52.1.1, ExQuilla 52.1.1180, EWS Provider 4.0.0-beta4

**Comment by digulla** [comment]
Maybe copy the wiki pages of the old project or point to the old wiki from the README.

Setup for calendar is described here: https://github.com/Ericsson/exchangecalendar/wiki/How-to-Add-Your-Calendar-to-Thunderbird

**Comment by advancingu** [comment]
Hi @digulla, thanks for the suggestion. You are right that there is no documentation in this fork at the moment.
Personally, I don't believe much in Wiki pages for documentation as they tend to go stale and out of sync with the software over time. Instead, I would propose to create an installation section in the `README.md` file that covers this topic.
Would you be able to submit a pull request for this? We are stretched a bit thin for resources.
Thanks.

**Comment by normic** [comment]
Hi @advancingu, I agree with you, that wiki pages get outdated sometimes (maybe often).
But the referenced docs are quite long and comprehensive, this would make the readme much more than just a quick overview.
I can create a wikipage here, rework the referenced document(s) and after that put a section with a link in the `README.md` .
I would be glad if I could help, as this is a really important project.

**Comment by advancingu** [comment]
@normic If you find that documentation would be too long for README.md, I suggest creating a `doc` folder and putting separate markdown files in there.
If opened a new issue to track documentation in #104.
