### ISSUE TITLE
Contributing Czech translation

### ISSUE THREAD

**Issue by p-bo** [ExchangeCalendar/exchangecalendar#52]
[cs-CZ.zip](https://github.com/ExchangeCalendar/exchangecalendar/files/1135587/cs-CZ.zip)

Hi, sorry for doing it this way - forking and doing pull request is far to complicated for mere translator ;-)
BTW - what about exposing translation in some translation tool/service (weblate, transifex...)? It would attract even more translators...

Pavel

**Comment by advancingu** [comment]
Hi Pavel, thanks for the contribution. I'll see that this gets integrated in the next release.

In the meantime, would you be able to make some suggestions as to which tools specifically would work well for a project like this one here and how such a tool has been integrated in similar projects?

**Comment by advancingu** [comment]
@p-bo Fyi, Transifex rollout is now in progress.

**Comment by p-bo** [comment]
@advancingu Great - thanks for letting me know :-)

**Comment by advancingu** [comment]
@p-bo You should now be able to request access as a translator for the Transifex project at https://www.transifex.com/exchangecalendar/exchangecalendar

**Comment by p-bo** [comment]
Great :)
Could you approve my request for joining on Transifex please?
Pavel Borecki

**Comment by advancingu** [comment]
Done, thanks!

**Comment by advancingu** [comment]
I'll close this now that Transifex is in place (even though I personally don't yet know how the strings over there will get integrated here when we create new builds).

**Comment by Trim** [comment]
@advancingu tbefore creating new builds, we'll have to use the Transifex client to pull changes from Transifex and apply them to our source code (the configuration file added to the source code does the match between Transifex resources and source code tree). Then, we'll have to manually commit changes made by the transifex client.

**Comment by advancingu** [comment]
Ok, works for me. This can be done via the regular PR process.
