### ISSUE TITLE
Error during checking of server and mailbox: HTTP Client error 401: Unauthorized URL:https://outlook.office365.com/EWS/Exchange.asmx

### ISSUE THREAD

**Issue by chorus12** [ExchangeCalendar/exchangecalendar#55]
Hello, I am using office365 for business and wanted to configure GAL to be in sync with TB. 
When configuring the account get the following error:
Error during checking of server and mailbox: HTTP Client error 401: Unauthorized
URL:https://outlook.office365.com/EWS/Exchange.asmx

**Comment by rucoder** [comment]
I have the same issue. Either add-on cannot fetch password from outlook account settings or... btw, Why don't just let user enter password?

**Comment by advancingu** [comment]
Hi, this appears to be a duplicate of #49.
