### ISSUE TITLE
How to Add Shared Calendars

### ISSUE THREAD

**Issue by BGMcoder** [ExchangeCalendar/exchangecalendar#58]
It is easy enough to add a personal calendar (which I can do, too), but how about a shared calendar that is created in the domain's public folders?

How does one get the "Share Folder Id" ?
I've tried using the location \\Public Folders - me@my.email\All Public Folders\theCalendar
I've also tried every combination of parts from this location to use as the shared folder id.  I got this "location" by right-clicking the properties of the shared folder item in Outlook.

**Comment by Trim** [comment]
Hello,

What do you mean by "domain public folders" ? Are they linked to a mailbox, like `company@domain` ?

If that's the case, you have to set as mailbox this one and as user your authentication settings. Then you'll be able to select folder, like the "Root mailbox folder" and then browse path from this one.

The shared folder id is not necessary if you have such configuration: it seems to be given in sharing mail invitations, but I'm not sure as I never used them.

**Comment by BGMcoder** [comment]
Hi, Trim.  When you are in Exchange online in the admin center, there is the section for `public folders` - there you can create a public folder mailbox and put a public folder in it.  The path to these folders is simply at `\` - so, I have `\Global Calendars`.  If you don't enable the the mail function on it, you can still use it as an exchange folder that appears in everyone's Outlook (in public folders).  There you can put public calendars.
So the folders have a definite location, but not an email account - and there are calendars there.

**Comment by Trim** [comment]
Ok, I understand what you need, but my available Exchange servers don't have this feature enabled.

Maybe, you could you try this steps:

- set the exchange web service url
- set your mail as primary email address
- set your mail as user name (or your authentication identifier if they are different)
- Click on the button to verify the settings
- In the appeared folder list, choose "Public folders"
- Then click on the "Browse" button below

If I have well understood the user interface, you should see all public folders there.

Aside that, I'm currently reading the Microsoft documentation about the functions used by "Shared folder id" which may help in this case.

**Comment by BGMcoder** [comment]
Trim, thank you for your time!  Voila!  That was it!  Thank you so much!  (I could hug you)

**Comment by advancingu** [comment]
Closing, as the original request appears to have been solved.
