### ISSUE TITLE
Where is the wiki for this project?

### ISSUE THREAD

**Issue by tallship** [ExchangeCalendar/exchangecalendar#65]
I just found this repo/fork of the project the other day when I received an email about an issue that was opened related to breakages in the ericsson version that this project was forked from. The wiki for that project is here: https://github.com/Ericsson/exchangecalendar/wiki - but there's no wiki link for this project although it is mentioned in the README.md file...

What I find confusing is the requirement to compile with other components. I don't understand why a  plugin wouldn't be available as a plugin, especially since most people wishing to integrate exchange services with Thunderbird/Lightning (which Lightning is now properly part of Thunderbird and not separate) are running Windows operating systems with no Bash shell or other utilities to compile source code.

Regardless of whether someone is running Solaris or BSD or Linux or Windows.... Shouldn't there just be a single .xpi file to install in Thunderbird?

I realize that's two questions, first, where is the wiki for this project, and two, why does the README.md indicate that someone must compile the plugin instead of just downloading the .xpi file?

Any assistance would be greatly appreciated.

**Comment by Trim** [comment]
Hello,

This fork is really new and we don't have all tools up (like documentation, translation, ...)

The documentation is a good question: first we don't have enough man power to create ourself a documentation and secondly someone has noticed that wiki aren't enough to document and follow evolutions (they are often outdated). So we need a way to create a good documentation which will follow code releases and that's certainly by adding a "doc" directory inside the plugin directly.

Note, that even the code has almost no documentation. I'm trying to add comments when I modify some parts, but there's a lot to do and I'm not really sure of what was meant, what is really done finally,... This project relies upon an undocumented legacy code sadly :s

Finally, the need to "compile" the plugin (in fact, that's just a zip file creation then renamed as xpi) is only needed if you want to use latest devlopments available on master. If you just want to get latest plugin release, see the [release page](https://github.com/ExchangeCalendar/exchangecalendar/releases).

**Comment by normic** [comment]
@Trim I understand the problems arising with undocumented code and I generally agree with the concern that wiki pages may outdate soon. 

But in my opinion this project is mainly not for coders it's for users and therefore I would suggest keeping the userdocs in the wiki and the coderdocs in the code. Furthermore I think a lot of internal code changes wil not affect the UI and so won't need an update of the wiki pages...

As mentioned in #50 I offer my help in recreating wiki pages here. I'm convinced that this will help making this project easy usable for every user. Unfortunately I cannot help with the code, as I'm not the Javascript coder.

**Comment by tallship** [comment]
@Trim @normic perhaps attention to publishing to the wiki followed by generating an html doc tree or plain text doc/ from the wiki or vice versa to accommodate both suggestions?

There's a lot of merit, and ity looks much more professional to have the wiki - updates can be made in conjunction with feature and configuration changes, and of course any software should be delivered with docs, even if they're just the main features in a single large readme with links back to the wiki page, or sections thereof.

It would bee nice to see the wiki moved over, even with edits i imagine it would be simpler to use the existing framework.

Any ideas as to how one might convert the wiki text to ascii/text or some other format with indexing?

**Comment by advancingu** [comment]
Hi everyone.

I'm really not in favour of enabling the Github wiki as it unnecessarily ties the project to Github. A better solution is to simply create a documentation folder and submit Markdown formatted documentation files via pull requests. That way the documentation can also always stay in sync with the corresponding code.

@normic Going ahead and starting this on the `ec-4.0` branch would be great. See for example #58.

Thanks.
