### ISSUE TITLE
"Save and close" vs. "save"

### ISSUE THREAD

**Issue by ontheair81** [ExchangeCalendar/exchangecalendar#9]
Hello everybody,
this is my setup on the computer at the office:
_Exchange EWS Provider - 4.0.0-beta1
Lightning 5.4.1.1
Thunderbird 52.1.1
Windows7Pro
Using exchange calendar and CalDAV calendars in parallel._

When adding a date or task (regardless if adding to Exchange or to CalDAV) I just see the button "save" (which was "save and close" in older versions).

On my home computer I have the exact same setup, but without Exchange EWS Provider - 4.0.0-beta1.
If adding a date or task to CalDAV there is still "safe and close".

Is it true, that the change from "save and close" to "save" was introduced with the new Exchange EWS Provider? It looks like that, because without this addon its still "save and close" (which is, in my opinion, a much better and consistent way to handle that).

Thank you for informations or help!

**Comment by Trim** [comment]
Hello,

Thunderbird allows you to edit the bar with tool buttons: if you make a right click on the bar, you can select "Personalize" (or something like that). Then you see a window with all available buttons. From this window you can drag and drop buttons in the tool bar.

Indeed there's 2 buttons to save your work "save" or "save and close", but they come from Thunderbird directly, not this extension.

One thing, this extension does is to modify the "Add attachment" button to allow to add document to task/event.

I've checked with a new Thunderbird profile and one with this extension and I confirm the extension modify choice of save button. I find better too the "save and close" button.

Thanks for the report, I'll check what I can do to have a better toolbar.

**Comment by ontheair81** [comment]
Thank you for confirming that this extension is modifying the button.
And even more: Thank you for the hint about changing it back ;-)

**Comment by advancingu** [comment]
Should be fixed in [v4.0.0-beta2](https://github.com/ExchangeCalendar/exchangecalendar/releases/tag/v4.0.0-beta2).
